### ISSUE TITLE
Google Takeout Error - Import "location-history.json" failed: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by davisdeatonphotography** [Freika/dawarich#103]
**Describe the bug**
Cannot import location-history.json files from Google Phone Takeout

**Version**
0.8.3

**To Reproduce**
1. Go to imports
2. Click on new import
3. Scroll down to "Google Phone Takeout"
4. Upload location-history.json
5. Press import
6. Notification alerting the import failed

**Expected behavior**
My Google takeout location should have been imported to docker.

**Screenshots**
<img width="915" alt="Screenshot 2024-07-05 at 8 42 56 PM" src="https://github.com/Freika/dawarich/assets/130251632/b62ac1e2-dc6c-4308-94a2-cd18c12c379d">
<img width="1317" alt="Screenshot 2024-07-05 at 8 42 51 PM" src="https://github.com/Freika/dawarich/assets/130251632/1bd598e4-9f27-4fc1-b3d6-5ae5bc62c0a7">
<img width="863" alt="Screenshot 2024-07-05 at 8 42 34 PM" src="https://github.com/Freika/dawarich/assets/130251632/adc5d00a-169a-4a1b-84b8-e9301c39c9c7">
<img width="998" alt="Screen Shot 2024-07-05 at 8 42 21 PM" src="https://github.com/Freika/dawarich/assets/130251632/166c2e3d-4884-4d4a-a5f8-df4d1930aae1">

**Logs**
The logs are ginormous, and I can't include them here.  The notification says, "Import "location-history.json" failed: no implicit conversion of String into Integer."

**Additional context**
I haven't been able to use this app with Google Takeout yet, and I've tried daily for the last couple of weeks.  The rest of the app is impressive, though, and precisely what I was looking for!  Looking forward to supporting the full app soon.

**Comment by truongty** [comment]
I am having the same issue.

**Comment by Freika** [comment]
@truongty @davisdeatonphotography this should have been solved in 0.8.4, please try to update and import again.

**Comment by truongty** [comment]
> @truongty @davisdeatonphotography this should have been solved in 0.8.4, please try to update and import again.

Excellent. Works for me now, thanks!
