### ISSUE TITLE
Arugments Location Format

### ISSUE THREAD

**Issue by gTamatea** [Freika/dawarich#104]
**Describe the bug**
It's not really a bug but I would like to know the precise format that dawarich is waitng. I just get "ActiveRecord::RecordInvalid: Validation failed: Latitude can't be blank, Longitude can't be blank"

**Version**
8.1

**To Reproduce**
See the error in sidekiq when receiving a location  update

**Expected behavior**
No error when Dawarich receive a location update

**Screenshots**
N/A

**Logs**
Owntracks::PointCreatingJob

{"{\"_type\":\"location\",\"acc\":48,\"alt\":86,\"batt\":\"41\",\"conn\":\"w\",\"lat\":40.881283,\"lon\":1.3575878,\"tid\":\"phone\",\"tst\":1020106901,\"vac\":2,\"vel\":0,\"cog\":170}"=>nil, "api_key"=>"xxx redacted xxx", "controller"=>"api/v1/owntracks/points", "action"=>"create"}, 1

ActiveRecord::RecordInvalid: Validation failed: Latitude can't be blank, Longitude can't be blank

**Additional context**
Thanks for you help

**Comment by Freika** [comment]
Hi @gTamatea! Can I ask you to include more logs from containers surrounding the error? Thank you!

**Comment by gTamatea** [comment]
> Hi @gTamatea! Can I ask you to include more logs from containers surrounding the error? Thank you!

Hello thanks for your answer. In fact I was using json message and not http as I misread my configuration. Everything seems ok now :)

**Comment by Freika** [comment]
Closing this then!

**Comment by tigattack** [comment]
> > Hi @gTamatea! Can I ask you to include more logs from containers surrounding the error? Thank you!
> 
> Hello thanks for your answer. In fact I was using json message and not http as I misread my configuration. Everything seems ok now :)

Could you elaborate on this? I'm seeing the same error and not sure what's wrong as I'm POSTing my location updates to dawarich in the same way as I do to my owntracks recorder.

**Comment by gTamatea** [comment]
Hello, I'm using homeassistant with node-red to post a message to dawarich.

BEFORE
`// Construct msg.payload as a JavaScript object
msg.payload = {
    _type: 'location',
    acc: gps_accuracy,
    alt: altitude,
    batt: battery_level,
    conn: connection_type,
    lat: latitude,
    lon: longitude,
    tid: tracker_id,
    tst: timestamp,
    vac: vertical_accuracy,
    vel: velocity,
    cog: course,
};

// Convert msg.payload to minified JSON
msg.payload = JSON.stringify(msg.payload);`

AFTER (disable json)
`// Construct msg.payload as a JavaScript object
msg.payload = {
    _type: 'location',
    acc: gps_accuracy,
    alt: altitude,
    batt: battery_level,
    conn: connection_type,
    lat: latitude,
    lon: longitude,
    tid: tracker_id,
    tst: timestamp,
    vac: vertical_accuracy,
    vel: velocity,
    cog: course,
};

// Convert msg.payload to minified JSON
//msg.payload = JSON.stringify(msg.payload);`

**Comment by tigattack** [comment]
Handy, I'm using it the same way. Omitting `JSON.stringify` solved it for me too, thanks!
