### ISSUE TITLE
dawarich_sidekiq exited with code 1

### ISSUE THREAD

**Issue by MrColumbo** [Freika/dawarich#105]
not quite sure about the impact but the sidekiq container loops  - starts and terminates all the time

**Version**
0.83

**To Reproduce**
deploy with latest default docker compose and start

Logs

dawarich_db (172.20.0.2:5432) open
ERROR:  Loading command: update (LoadError)
	cannot load such file -- /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/vendored_optparse
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:9:in `require_relative'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:9:in `<top (required)>'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/commands/update_command.rb:3:in `require_relative'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/commands/update_command.rb:3:in `<top (required)>'
	<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:236:in `load_and_instantiate'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:137:in `[]'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:209:in `find_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:251:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'
ERROR:  While executing gem ... (NoMethodError)
    undefined method `deprecated?' for nil:NilClass

    cmd.deprecation_warning if cmd.deprecated?
                                  ^^^^^^^^^^^^
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'
Environment: development
dawarich_db (172.20.0.2:5432) open
ERROR:  Loading command: update (LoadError)
	cannot load such file -- /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/vendored_optparse
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:9:in `require_relative'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/command.rb:9:in `<top (required)>'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/commands/update_command.rb:3:in `require_relative'
	/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/commands/update_command.rb:3:in `<top (required)>'
	<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:236:in `load_and_instantiate'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:137:in `[]'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:209:in `find_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:251:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'
ERROR:  While executing gem ... (NoMethodError)
    undefined method `deprecated?' for nil:NilClass

    cmd.deprecation_warning if cmd.deprecated?
                                  ^^^^^^^^^^^^
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
	/usr/local/bin/gem:10:in `<main>'

**Comment by Freika** [comment]
@MrColumbo can you try to update to the most recent version of Dawarich and let me know if this is still a case? Thank you.

**Comment by MrColumbo** [comment]
now it works fine - sidekick is running and imports are actually getting imported. Thanks a lot!
