### ISSUE TITLE
Feature requests: allow multiple hosts

### ISSUE THREAD

**Issue by ghost** [Freika/dawarich#108]
I only expose the api path via my reverse proxy to the public internet and use an internal domain to access dawarich.
Unfortunately that means at the moment to switch back and forth the allow-host env. var in the docker compose file which is a bit cumbersome.

As per this comment, multiple values would be greatly appreciated: https://github.com/Freika/dawarich/issues/76#issuecomment-2192426209

Many thanks for dawarich, brilliant app so far!!

**Comment by Freika** [comment]
Hi @abmurksi! You can try setting it in `APPLICATION_HOSTS` env var, it was implemented in 0.8.4 release: https://github.com/Freika/dawarich/releases/tag/0.8.4
