### ISSUE TITLE
Without changing to APPLICATION_HOSTS, stack won't start

### ISSUE THREAD

**Issue by TheBig-O** [Freika/dawarich#110]
**Describe the bug**
The latest update breaks the containers where "APPLICATION HOST" variables exist. It must be "APPLICATION HOSTS" as noted only as recommended.

**Version**
0.8.4

**To Reproduce**
1. Update to current release version and restart containers without changing anything.

**Expected behavior**
I expected both the App add Sidekiq to start as normal.

Recommend adding a "Breaking Change" note to the release comments and specify a required update to the compose files.

**Comment by Freika** [comment]
Log from a container would help a lot, although I think I figured it out myself and fixed in https://github.com/Freika/dawarich/releases/tag/0.8.5 :)

**Comment by AdamSnow** [comment]
I think I'm having the same issue, with this portion from the logs. Looks like WatchTower noticed the new version, but things still aren't launching anymore.

```
NoMethodError: undefined method `split' for ["localhost"]:Array (NoMethodError)

  config.hosts.concat(hosts.split(',')) if hosts.present?
                           ^^^^^^
```

**Comment by Freika** [comment]
Hi @AdamSnow! It have been fixed in the latest version, please try to update and start the app

**Comment by TheBig-O** [comment]
> Log from a container would help a lot, although I think I figured it out myself and fixed in https://github.com/Freika/dawarich/releases/tag/0.8.5 :)

Sorry about that. I was away from my computer, on my phone and was attempting quick fixes during a trip. 
Thanks for the great work on this! Really enjoying it.
