### ISSUE TITLE
Feature requests: disable map auto-refresh on update

### ISSUE THREAD

**Issue by etuck** [Freika/dawarich#112]
I'm using OwnTracks to update fairly frequently. Every time DaWarich receives an update it resets my location on the map.  It would be nice to be able to temporarily disable that refresh in the UI.

**Comment by Freika** [comment]
@etuck not sure if I got the problem, can you provide more details? Thanks

**Comment by etuck** [comment]
When I view the map and scroll to a different location, zoom, etc., it automatically resets to the starting point every 20 or so seconds.  I assume that's happening because another data point uploaded from OwnTracks has been processed. I don't thing the map was doing that before I configured OwnTracks. I suppose it could be for other reasons but in any event, I'd like to be able to stop that refresh/reset while I'm actively moving the map.

**Comment by Freika** [comment]
Dawarich doesn't have any features related to map refreshing without actions from the user's side. The map might move only when you move it or if you hover over a route, the finish point of which lies outside of the current map frame, in that case map will be moved to render that point.

**Comment by Freika** [comment]
It was fixed in 0.9.2: https://github.com/Freika/dawarich/releases/tag/0.9.2
