### ISSUE TITLE
Can't import from new Google timeline.

### ISSUE THREAD

**Issue by ve3** [Freika/dawarich#113]
**Describe the bug**
Due to the new Google timeline is not available on PC* web browser any more, it is available on app only. I can export data use Google takeout but I don't see **Records.json**.
When I try to import (any available files), I stuck at this command -> `bundle exec rake import:big_file`. with error message 
> Don't know how to build task 'import:big_file[Timelineedits.json,'

**Version**
0.8.6

**To Reproduce**
1. Go to [Google Takeout](https://takeout.google.com/settings/takeout)
2. Follow the export process the same on your [wiki](https://github.com/Freika/dawarich/wiki/How-to-import-your-Google-Takeout-data) until step **9**. There is no file named **Records.json**.
3. Try to upload, copy, import any available json files (try one by one).
4. None of them (json files) be able to run `bundle exec rake import:big_file` command.

**Expected behavior**
I hope that there is at least one of them be able to import but it's not.

**Screenshots**
No

**Logs**

> Don't know how to build task 'import:big_file[Timelineedits.json,' (See the list of available tasks with `rake --tasks`)
> /var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task_manager.rb:59:in `[]'
> /var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:187:in `invoke_task'/var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
> /var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
> /var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
> /var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
> /var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
> /var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:83:in `block in run'/var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
> /var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
> /var/app/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
> /var/app/vendor/bundle/ruby/3.2.0/bin/rake:25:in `load'
> /var/app/vendor/bundle/ruby/3.2.0/bin/rake:25:in `<top (required)>'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
> /usr/local/bundle/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
> /usr/local/bundle/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
> /usr/local/bundle/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
> /usr/local/bundle/bin/bundle:25:in `load'
> /usr/local/bundle/bin/bundle:25:in `<main>'

**Additional context**
No

***Reference**
[1](https://support.google.com/maps/thread/254868591/timeline-is-no-longer-available-on-web-browsers?hl=en)
[2](https://www.reddit.com/r/GoogleMaps/comments/18mjrmx/timeline_no_longer_supported_on_desktop/)
[3](https://support.google.com/maps/thread/261255548/google-timeline-is-can-not-be-visible-on-the-web-browser-how-can-we-see-the-google-timeline-again?hl=en)

**Comment by Freika** [comment]
Hi @ve3! Can you show files and directory structure of your Takeout? Thanks

**Comment by ve3** [comment]
Takeout
|--ประวัติตำแหน่ง (ไทม์ไลน์)
.....|--Encrypted Backups.txt
.....|--Settings.json
.....|--Timeline Edits.json
.....|--Tombstones.csv
|--archive_browser.html

**Comment by ve3** [comment]
New Google time line use new way to export and [here is instruction](https://support.google.com/maps/thread/264641290/export-full-location-timeline-data-in-json-or-similar-format-in-the-new-version-of-timeline?hl=en).

However, I'm currently stuck with their [**export failed**](https://support.google.com/maps/thread/280068252/unable-to-access-timeline-gdpr-access-required-by-law?hl=en).

**Comment by Freika** [comment]
> Takeout |--ประวัติตำแหน่ง (ไทม์ไลน์) .....|--Encrypted Backups.txt .....|--Settings.json .....|--Timeline Edits.json .....|--Tombstones.csv |--archive_browser.html
> 
> When I copy file to docker, I renamed **Timeline Edits.json** to be **Timelineedits.json**.

I'm not sure what can be imported from this Takeout, it seems basically empty to me. Are there any files bigger than several kilobytes?

**Comment by ve3** [comment]
The new timeline is can't export from takeout anymore. It has been moved to user's phone (and in Google backup which can't import from that).
To export from phone, please follow instruction [here](https://support.google.com/maps/thread/264641290/export-full-location-timeline-data-in-json-or-similar-format-in-the-new-version-of-timeline?hl=en).
But it may stuck at export failed.

**Comment by tylwright** [comment]
I can take this as an action item to create a wiki page on this.  As of a few minor releases ago, the new "phone app dump" is supported as an import method.  I should have the doc in an hour or so and will post a link here when it gets merged up!

**Comment by tylwright** [comment]
Looks like forking GitHub Wikis isn't really a thing.  I have my proposed change.  @Freika - Would you be okay granting me granting me wiki edit privs, if possible?  Otherwise, I have my wiki addition here: [https://github.com/tylwright/dawarich/wiki/How-to-import-your-Google-Maps-Timeline-data](https://github.com/tylwright/dawarich/wiki/How-to-import-your-Google-Maps-Timeline-data).

**Comment by ve3** [comment]
I can import using web UI (imports page) now. Based on @tylwright URL and it is easier (different) than using command in [wiki page](https://github.com/Freika/dawarich/wiki/How-to-import-your-Google-Takeout-data).

It is currently running imports process (very long time now).

Please update wiki on official page. 🙂

However, I'm still stuck on export location on Android with **export failed** error but that is Google problem not dawarich.

**Comment by tylwright** [comment]
Thanks, @Freika!

Official wiki has been updated: https://github.com/Freika/dawarich/wiki/How-to-import-your-Google-Maps-Timeline-data

**Comment by ve3** [comment]
The step to export/download timeline data on Android is [on this link](https://support.google.com/maps/thread/264641290/export-full-location-timeline-data-in-json-or-similar-format-in-the-new-version-of-timeline?hl=en).

Maybe update to wiki?

I'll close this issue as it is be able to import with new Google timeline now.
