### ISSUE TITLE
sidekiq interface open to public

### ISSUE THREAD

**Issue by pmatis** [Freika/dawarich#120]
**Describe the bug**
I deployed in docker compose and use a reverse proxy to expose all on port 3000 behind a HTTPS host for my use. I just found that going to https://dawarich.apps.mydomain.com/sidekiq loads the interface even when I'm lot logged in. This allows job manipulation as well. I think we need to seriously consider securing this.

**Version**
I'm using 0.8.7 according to the UI, but it's not releases yet? Docker compose pulled it with:
```
  dawarich_app:
    image: freikin/dawarich:latest
```

**To Reproduce**
1. Visit your dawarich login page (Log out if you're already logged in)
2. Change the end of the URL to /sidekiq
3. See stats and have control without logging in

**Expected behavior**
This should not be exposed to the public interface, and if it is, it should be secured as a minimum
For not, I adjusted my reverse proxy to respond with 404 if I visit this URL

**Comment by Freika** [comment]
Implemented in https://github.com/Freika/dawarich/releases/tag/0.9.3
