### ISSUE TITLE
Feature Request: Edit points in map

### ISSUE THREAD

**Issue by chrisl8** [Freika/dawarich#127]
Sometimes it is visually obvious that a point is bad. It would be wonderful to be able to select that point from the map and delete it.

![image](https://github.com/user-attachments/assets/a05d3430-60ae-47db-a5bf-0d7b8817c7b2)

Of course, some automated exclusion of such points would be handy too, but that seems like a larger problem. The ability to just select points visually and edit/delete them would still be desirable.

**Comment by Freika** [comment]
This is already requested [here](https://github.com/Freika/dawarich/discussions/51) and planned to be implemented in the future :)
