### ISSUE TITLE
Can't import google data

### ISSUE THREAD

**Issue by fayak** [Freika/dawarich#13]
Hello !

importing my `Records.json` file from Google doesn't work. The application doesn't yield a message, but when I go to `/imports` I can see the import.
It doesn't contain anything apparently, and I'm not sure which file I have to upload.
I tried `Records.json` (which is 900MiB), the .zip directly downloaded from Google, or a single month from the Semantic Location History folder, none of them seems to be accepted by Dawarich, as they are all displayed as `✅ 0/0` in the /imports tab.

What is the expected file there ?

**Comment by Freika** [comment]
@fayak can you please provide logs from `dawarich_sidekiq` container?

**Comment by Meyu-Sys** [comment]
I'm having the same issue the log from `dawich_sidekiq` is
```
pid=32 tid=2f3c WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","wrapped":"ImportJob","args":[{"job_class":"ImportJob","job_id":"f9cbd000-37eb-44f3-beb5-cf8652640f96","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[1,60],"executions":0,"exception_executions":{},"locale":"en","timezone":"Europe/Berlin","enqueued_at":"2024-04-24T11:30:25.555374444Z","scheduled_at":"2024-04-24T11:30:30.555150845Z"}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"924d407b61bcb07240cafbc6","created_at":1713958225.555437,"enqueued_at":1713958339.6999114,"error_message":"ActiveStorage::FileNotFoundError","error_class":"ActiveStorage::FileNotFoundError","failed_at":1713958233.6422677,"retry_count":2,"retried_at":1713958288.4077744}}
```

**Comment by Freika** [comment]
This should be fixed in #21, @Meyu-Sys @fayak can I ask you to check out version 0.1.9?

**Comment by Meyu-Sys** [comment]
That fixed it.
PS the docker-compose file uses v0.1.6 tag for its container images instead of latest

**Comment by Freika** [comment]
@Meyu-Sys will be fixed in next release :)
