### ISSUE TITLE
OIDC SSO Authentication Support (Authentik, Authelia etc)

### ISSUE THREAD

**Issue by samtate** [Freika/dawarich#133]
**Describe the bug**
Many people run Authentik, Authelia etc to have a single sign on (SSO) across all their self hosted apps. This means there can be one account with a secure password and multi factor authentication and the self hosted apps use this service for authentication. As far as I can tell, Dawarich currently only supports simple username and password login.

**Version**
0.9.4

**Expected behavior**
There should be a configuration option, either in the ENV variables or in the settings GUI to set up an OIDC provider issuer URL, client ID, client secret etc.

Appreciate this software is currently in alpha so this may not be a priority but it would be a nice feature to have down the line.

**Comment by Freika** [comment]
Already requested: https://github.com/Freika/dawarich/discussions/66
