### ISSUE TITLE
Date time format for date search inputs

### ISSUE THREAD

**Issue by tetebueno** [Freika/dawarich#137]
**Describe the bug**
Currently the only date time format shown is `MM/DD/YYYY, h:mm:ss a`.

**Version**
0.9.4

**To Reproduce**
1. Log into the app.
2. See date time inputs.

**Expected behavior**
To be able to either configure the locale used when deploying or to choose it on settings section.

**Screenshots**
N/A

**Logs**
N/A

**Additional context**
There are places where the 24 hour and the DD/MM/YYYY format is more common.

**Comment by Freika** [comment]
It depends on your browser settings I guess.

My own example:

<img width="433" alt="изображение" src="https://github.com/user-attachments/assets/5d222400-e320-4ca4-89f4-e3717d4b8947">

**Comment by tetebueno** [comment]
Dumbest bug ever issued. Sorry and thanks.

**Comment by makanimike** [comment]
FWIW, I really do not like it when apps blindly follow regional settings of the OS or browser. I would much prefer in app control over time and date formats.  
At the same time, I understand I am probably a rare case: someone who prefers US English menus and interfaces on tech devices, but global / Euro / scientific data formats.

**Comment by Freika** [comment]
> FWIW, I really do not like it when apps blindly follow regional settings of the OS or browser. I would much prefer in app control over time and date formats.  
> 
> At the same time, I understand I am probably a rare case: someone who prefers US English menus and interfaces on tech devices, but global / Euro / scientific data formats.

There will be options to select at some point, just not a priority right now. But prs are welcome!
