### ISSUE TITLE
Rake Task for importing Records.json Killed

### ISSUE THREAD

**Issue by TheDoor** [Freika/dawarich#140]
**Describe the Bug**
When attempting to upload a large `Records.json` file (1.4GB) by following the instructions on [this page](http://localhost:3000/imports/new), the import process is unexpectedly terminated with the message "Killed."

**Version**
0.9.4
**To Reproduce**
1. Copy the `Records.json` file to the designated location: `dawarich_app:/var/app/public/imports/Records.json`.
2. Attach to the Docker container using the provided command.
3. Execute the rake task using the correct user email.

**Expected Behavior**
The `Records.json` file should be imported successfully, even if it takes a considerable amount of time.

**Logs**
/var/app # bundle exec rake import:big_file['public/imports/Records.json','mail@mail.com']
[dotenv] Set DATABASE_PORT
[dotenv] Loaded .env.development
W, [2024-07-26T15:55:44.286275 #98]  WARN -- : DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2. (called from <main> at /var/app/config/environment.rb:5)
D, [2024-07-26T15:55:44.891713 #98] DEBUG -- :   User Load (3.4ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "mail@mail.com"], ["LIMIT", 1]]
D, [2024-07-26T15:55:44.893409 #98] DEBUG -- :   ↳ lib/tasks/import.rake:9:in `block (2 levels) in <main>'
D, [2024-07-26T15:55:45.049454 #98] DEBUG -- :   TRANSACTION (0.7ms)  BEGIN
D, [2024-07-26T15:55:45.050996 #98] DEBUG -- :   ↳ lib/tasks/import.rake:13:in `block (2 levels) in <main>'
D, [2024-07-26T15:55:45.055057 #98] DEBUG -- :   Import Create (6.2ms)  INSERT INTO "imports" ("name", "user_id", "source", "created_at", "updated_at", "raw_points", "doubles", "processed", "raw_data") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["name", "public/imports/Records.json"], ["user_id", 2], ["source", 2], ["created_at", "2024-07-26 15:55:45.047090"], ["updated_at", "2024-07-26 15:55:45.047090"], ["raw_points", 0], ["doubles", 0], ["processed", 0], ["raw_data", nil]]
D, [2024-07-26T15:55:45.056352 #98] DEBUG -- :   ↳ lib/tasks/import.rake:13:in `block (2 levels) in <main>'
D, [2024-07-26T15:55:45.086478 #98] DEBUG -- :   TRANSACTION (29.5ms)  COMMIT
D, [2024-07-26T15:55:45.088082 #98] DEBUG -- :   ↳ lib/tasks/import.rake:13:in `block (2 levels) in <main>'
"Importing public/imports/Records.json for mail@mail.com, file size is 1455695961... This might take a while, have patience!"
Killed

**Comment by Freika** [comment]
Most likely, your container ran out of memory, can you monitor it during next importing attempt?

**Comment by TheDoor** [comment]
I have freed up some memory, and the rake task succeeded during the next import attempt.

**Comment by hopeseekr** [comment]
For me, `dawarich_app` has a max memory of 2 GB:

```
/var/app # cat /sys/fs/cgroup/memory.max
2147483648
```

But my machine has 128 GB of memory, and over 85 GB free. 52 GB is "available" and not even used for cache.

My Records.json is 754 MB and the large import keeps getting killed:

> Command terminated by signal 9

In the `docker-compose.yml`, I had to comment this out:

```yaml
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '2G'
```

Then

```
docker compose down
docker compose up -d
docker compose exec dawarich_app sh
```

Then the import worked... It used 3.6 GB.
