### ISSUE TITLE
Visits display from old to new instead of new to old

### ISSUE THREAD

**Issue by sunstep** [Freika/dawarich#149]
**Describe the bug**
After creating an area, I noticed that the first page of visits are my oldest visits. While the last page are my most recent visits. I know this feature is still beta, but I just wanted to report on this. It makes more sense to me to show the most recent visits first on the first page, and then make it go older as you scroll down/ go to the next page.

**Version**
0.9.8

**To Reproduce**
1. Create area to get visits
2. Go to visits page

**Expected behavior**
The newest visits should be on the first page and it should become older as you scroll down and go to next pages.

**Screenshots**
![image](https://github.com/user-attachments/assets/615ba881-68e8-42d6-b178-b4d8e0f8207b)

The screenshot above shows how page 1 shows my 2022 visits and not 2024.

**Comment by Freika** [comment]
[0.9.9](https://github.com/Freika/dawarich/releases/tag/0.9.9) introduces ordering buttons for visits and points pages :)
