### ISSUE TITLE
Exports fail if no 'exports' folder exists and no folder is created by default.

### ISSUE THREAD

**Issue by HStep20** [Freika/dawarich#151]
**Describe the bug**
When trying to create an Export, if there is no pre-existing 'exports' folder, then it fails.

**Version**
0.9.8

**To Reproduce**
1. Create a new install with the provided docker-compse
2. Add a point
3. Create an export

**Expected behavior**
I would expect the export to succeed when started. I believe the first export should create the `exports` folder automatically if it is not present within the `public` volume set in the docker-compose file. Alternatively, add a line to the docker-compose for the exports folder so that it is explicitly created upon deployment.

**Comment by radh21301** [comment]
Thank you! I have been breaking my head on why it kept failing. Created the folder 'exports' inside the 'public' folder, and all works.

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/pull/255
