### ISSUE TITLE
Export to GPX (plus, bonus app compatability option)

### ISSUE THREAD

**Issue by HStep20** [Freika/dawarich#162]
Feature request, as opposed to bug - but being able to Export data points to GPX format would make this perfect. I use it to track my location and would love to be able to export them to use with my Mirrorless Camera files for GPS data tagging. 

I know there is a discussion about it where you mention you will work on it, but I wanted to make it a request here for easier tracking: https://github.com/Freika/dawarich/discussions/85

Right now, I use the app 'Geotag Photos 2' which can use a GPX file to tag photos, but they require that you use their app to create the GPX files. As an addition to this feature request, Id love it if the GPX files created by Dawarich were compatible with GeotagPhotos2 program to do the actual photo tagging. 

From my investigation of opening the .xml file the app provides, they put this on the second line of the gpx file: `<gpx creator="Geotag Photos http://www.geotagphotos.net/" version="1.0" xmlns="http://www.topografix.com/GPX/1/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd">` which allows their app to use the GPX file on desktops.

If there were a checkbox on the Dawarich export page which would inject this into the second line of the generated GPX file, it would be awesome and save a workflow step between downloading location history and geotagging photos :)

**Comment by Freika** [comment]
Introduced in [0.13.0](https://github.com/Freika/dawarich/releases/tag/0.13.0)
