### ISSUE TITLE
Every Import fails

### ISSUE THREAD

**Issue by ThoMagnum** [Freika/dawarich#163]
**Describe the bug**
If I import gpx file ´, no point will be found and I got the message "Import "*.gpx" failed: no implicit conversion of Symbol into Integer ."

**Version**
0.9.8

**To Reproduce**
1. Go to 'Imports'
2. Click on 'New Import'
3. Scroll down to 'GPX track file'
4. Select file via "Durchsuchen"
5. Click 'Create Import'

**Expected behavior**
I expect a import with several found points.

**Screenshots**

**Logs**
See attached logs, I could not see an issue.

**Additional context**
[logs.txt](https://github.com/user-attachments/files/16535536/logs.txt)

**Comment by ThoMagnum** [comment]
Seems there was an issue with my used test-gpx files.

**Comment by Freika** [comment]
@ThoMagnum I'm aware this might happen if your gpx routes are planned one, but not tracked one. The difference is planned ones might now have timestamps for each point, which is crucial to have.
