### ISSUE TITLE
Feature: Reverse Proxy Support

### ISSUE THREAD

**Issue by snicker** [Freika/dawarich#164]
**Describe the feature**
Like many other users, I intend to run Dawarich behind a reverse proxy. Due to the current docker configuration, the steps for configuring this are a bit esoteric, and could be better supported natively in the configuration

**Version**
0.9.8

**To Reproduce**
1. Serve the local server behind a reverse proxy with any kind of domain/host (eg `dawarich.snicker.me`)
2. Attempt to access through the proxy @ http(s)://dawarich.snicker.me
3. Rails, by default, will throw an error for HostAuthorization

**Expected behavior**
Per documentation (https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization) there are multiple ways to solve this:
1. in the `development` environment, one can add authorized hosts to the `RAILS_DEVELOPMENT_HOSTS` environment variable (this is my fix since it can be done at the container level) 
2. if dawarich is not running in development (likely at some point) then the host must be explicitly added here:

```
Rails.application.config.hosts << "dawarich.snicker.me"
```
3. ideally this is configurable in the UI, a config file, or a dedicated environment variable (in config/application.rb)

**Comment by tylwright** [comment]
You can use the `APPLICATION_HOSTS` environment variable. Running this now via Caddy2 without any issues.

**Comment by snicker** [comment]
hm, I first tried adding my domain as a comma separated addition to "localhost", which didn't work. adding as the only value is working to serve, but I am now having trouble logging in (getting `422 unprocessable content` from the server)

would you mind sharing your Caddy2 config? I'm running through nginx, wonder if I need to adjust some headers

**Comment by snicker** [comment]
was able to get this working, but needed the following settings for my reverse proxy configuration in nginx:

```
proxy_http_version 1.1;
proxy_pass http://192.168.1.191:3555/;
proxy_set_header                Host                    $host;
proxy_set_header                X-Real-IP               $remote_addr;
proxy_set_header                X-Forwarded-For         $proxy_add_x_forwarded_for;
proxy_set_header                X-Forwarded-Proto       https;
proxy_set_header                Upgrade $http_upgrade;
proxy_set_header                Connection $connection_upgrade;
proxy_ssl_server_name           on;
```

previously I was missing 
```
proxy_set_header                X-Forwarded-Proto       https;
proxy_ssl_server_name           on;
```
