### ISSUE TITLE
Paths exposing information

### ISSUE THREAD

**Issue by tetebueno** [Freika/dawarich#166]
**Describe the bug**
Pages like /api-docs and Rails Action controller error page are exposed to unauthenticated users.

**Version**
0.9.8

**To Reproduce**
1. Go to https://your-dawarich-domain/api-docs or to any non-existing path like https://your-dawarich-domain/sruc
2. See content

**Expected behavior**
Non-authenticated users should be redirected to a generic error page without exposing information or to login screen.

**Screenshots**
Rails error page:

![image](https://github.com/user-attachments/assets/8fcd7ba2-95fb-494a-947f-bbd9111116f4)

**Logs**
```log
23:30:51 web.1  | F, [2024-08-08T23:30:51.765589 #46] FATAL -- :   
23:30:51 web.1  | ActionController::RoutingError (No route matches [GET] "/sruc"):
23:30:51 web.1  |   
23:30:51 web.1  | D, [2024-08-08T23:30:51.796021 #46] DEBUG -- :   Rendering layout vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/templates/rescues/layout.erb
23:30:51 web.1  | D, [2024-08-08T23:30:51.796085 #46] DEBUG -- :   Rendering vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
23:30:51 web.1  | D, [2024-08-08T23:30:51.820030 #46] DEBUG -- :   Rendering vendor/bundle/ruby/3.2.0/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
```

**Additional context**
N/A

**Comment by Freika** [comment]
This is a known aspect of the app being run in the development mode by default. It's not a subject of change in the near future

**Comment by tetebueno** [comment]
I see, is it recommended to run the app un production mode or is this something to be expected in future versions?

Thanks!

**Comment by Freika** [comment]
@tetebueno right now I'd say run it in development mode, that way if you see any bug, you'll probably will be able to see the error text as well.

It might change in future, yes.
