### ISSUE TITLE
update to 0.9.9 seems to fail - app reports 0.98 

### ISSUE THREAD

**Issue by MrColumbo** [Freika/dawarich#167]
i tried to update and got the message

dawarich_sidekiq Skipped - Image is already being pulled by dawarich_app

...and app reports as 0.98 instead of 0.99

....not quite sure if maybe the app just reports itself with the wrong version or if the update failed ....

**Comment by sunstep** [comment]
I reported the same issue on the Discord but got no reaction. I think the bug is only with the fact that it reports 0.9.8 instead of 0.9.9. 
I do have the features of 0.9.9. So it doesn't fail with updating, it just reports the wrong version.

**Comment by Freika** [comment]
I just forgot to update version, if your docker image is tagged 0.9.9, it's 0.9.9.
