### ISSUE TITLE
High CPU usage on latest version (0.9.12)

### ISSUE THREAD

**Issue by Artnal** [Freika/dawarich#175]
**Describe the bug**
I updated to the latest 0.9.12 this morning, and since then the CPU usage crashes my VM (2 cpu cores available). It spikes above 80%, sometimes reaching around 100%, which renders the VM unresponsives and/or crashes it. I rolled back to 0.9.11 for dawarich_app and dawarick_sidekiq, and the problem isn't there (CPU usage remains between 5-20%).

I have controlled for other docker containers, and it seems to be the culprit on its own.

**Version**
0.9.12

**To Reproduce**
1. Update to 0.9.12
2. CPU usage spikes above 80% (2 cores available for docker VM)
3. VM crashes at some point, or becomes unresponsive.

**Expected behavior**
No crashes of the VM due to Dawarich

**Logs**
I'm not at home currently, but if any logs are useful to you, I can look into it later today or tomorrow.

**Comment by Freika** [comment]
@Artnal 0.9.12 contains an intensive data migration that fills all points tracked from the Owntracks app with the missing data, see #165

After this data migration is finished, resource consumption should return to normal
