### ISSUE TITLE
Database and Redis shuts down by itself

### ISSUE THREAD

**Issue by sunstep** [Freika/dawarich#176]
**Describe the bug**
I have no idea what is the cause of the shutdowns, but I can tell that it is not the first time this has happened. 

**Version**
0.9.12

**To Reproduce**
I cannot really reproduce this. Sometimes I just go to my Dawarich instance, then I see it down with a 502 bad gateway page because the database and Redis has decided to shut itself down.

**Expected behavior**
The database and Redis should stay up as long as Dawarich is up

**Logs**
DB logs:
2024-08-16 10:40:08.117 UTC [1] LOG:  received fast shutdown request
2024-08-16 10:40:08.120 UTC [1] LOG:  aborting any active transactions
2024-08-16 10:40:08.121 UTC [31089] FATAL:  terminating connection due to administrator command
2024-08-16 10:40:08.136 UTC [1] LOG:  background worker "logical replication launcher" (PID 27) exited with exit code 1
2024-08-16 10:40:08.137 UTC [22] LOG:  shutting down
2024-08-16 10:40:08.225 UTC [1] LOG:  database system is shut down

Redis:
1:M 16 Aug 2024 10:33:57.003 * 100 changes in 300 seconds. Saving...
1:M 16 Aug 2024 10:33:57.004 * Background saving started by pid 2020
2020:C 16 Aug 2024 10:33:57.022 * DB saved on disk
2020:C 16 Aug 2024 10:33:57.023 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 16 Aug 2024 10:33:57.106 * Background saving terminated with success
1:M 16 Aug 2024 10:38:58.006 * 100 changes in 300 seconds. Saving...
1:M 16 Aug 2024 10:38:58.007 * Background saving started by pid 2021
2021:C 16 Aug 2024 10:38:58.025 * DB saved on disk
2021:C 16 Aug 2024 10:38:58.026 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 16 Aug 2024 10:38:58.108 * Background saving terminated with success
1:signal-handler (1723804808) Received SIGTERM scheduling shutdown...
1:M 16 Aug 2024 10:40:08.143 # User requested shutdown...
1:M 16 Aug 2024 10:40:08.143 * Saving the final RDB snapshot before exiting.
1:M 16 Aug 2024 10:40:08.150 * DB saved on disk
1:M 16 Aug 2024 10:40:08.150 # Redis is now ready to exit, bye bye...

**Comment by Freika** [comment]
I'm not sure why it happened, but thank you for the fix! Let's see how it goes, I'll close the issue for now, we'll reopen it later if necesary
