### ISSUE TITLE
'Select Year' button on Map page selects 'Selected Year - 1'

### ISSUE THREAD

**Issue by HStep20** [Freika/dawarich#194]
**Describe the bug**
When using the 'Select Year' button on the map page, it seems to filter points by the incorrect year. Each time I select a year, it actually selects the selected year minus one (2023 instead of 2024, 2022 instead of 2023, etc)

**Version**
0.11.1

**To Reproduce**
1. Go to Map page
2. Click 'select year' button on right column and select a year
3. See that points are filtered to the wrong year

**Comment by gboudreau** [comment]
The Stats page has the same issue.

For example, the links for 2023 are:
- 2023 : `/stats/2023` - OK
- Map : `/map?end_at=2022-12-31T23%3A59&start_at=2022-01-01T00%3A00` - Not OK

So clicking the Map link shows 2022, not 2023.

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.14.5, kudos to @gboudreau!
