### ISSUE TITLE
Update the points API documentation

### ISSUE THREAD

**Issue by sunstep** [Freika/dawarich#196]
I am currently on version 0.12.1, but I noticed that in the Swagger documentation at the points api it doesn't say anything about the newly added pagination features. 

![image](https://github.com/user-attachments/assets/f0e96ae8-f04c-4863-98cc-e4993ecc59a2)

I think it should be added as well to the documentation.

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.12.2
