### ISSUE TITLE
Feature Request: Configurable initial map time range

### ISSUE THREAD

**Issue by chrisl8** [Freika/dawarich#210]
Can this line be configurable somehow?

https://github.com/Freika/dawarich/blob/71434ae019a61e2526ff4c81df12ae671d5cb581/app/controllers/map_controller.rb#L23

As it is, when I open up the site, my browser has to download 40 megabytes of data! I know this is probably due to my poor setup of the Overland app, but by reducing the date range to just a week or a few days, it works much better for me.

Being able to set this initial load period would fix this I think.

For now I am just editing the code, but a configuration parameter in the settings would be great.

Thanks!

**Comment by Freika** [comment]
One of the recent releases changed default timeframe from 1 month to 1 day. This should be enough and will work better with large amount of points
