### ISSUE TITLE
Feature Request: Notification of loss of data

### ISSUE THREAD

**Issue by revenador** [Freika/dawarich#211]
As android does not allow location apps to automatically start on boot any more, it is very easy for tracking to be down for quite a while before it gets noticed.

If we could get some kind of notification that no location updates have been received in the last X hours or days it would allow us to correct any issues without too much loss of tracking data.

I haven't been using dawarich for very long but so far am quite impressed especially for a relatively new project

Thanks

**Comment by Freika** [comment]
There is no way to say for sure for a server, whether user not sending data on purpose or something's up with his client app. I also think it's the user's or device's responsibility to make sure data is being sent, not for the server to make sure it receives something. I don't think this will be implemented, or at least not in the form it is requested, sorry.
