### ISSUE TITLE
Import "created at" date format isn't consistent with other views

### ISSUE THREAD

**Issue by tyrrminal** [Freika/dawarich#213]
**Describe the bug**
The date format used on the Imports screen for the "created at" value doesn't match other date displays in the application

**Version**
0.12.3

**To Reproduce**
1. Import a file (gpx file in my case, if it matters)
2. Wait for import to complete
3. View imports list

**Expected behavior**
I would expect the date format to be ISO8601 (e.g., "2024-08-30 23:33:20 +0100") as this date format is used on the Points and Places screens. Instead, the date is shown like "30.08.2024, 23:33"

**Comment by Freika** [comment]
I wouldn't call it a bug, but I'll see if it'll make sense to unify datetimes representation in future
