### ISSUE TITLE
Feature Request: Delete points by import/track

### ISSUE THREAD

**Issue by tyrrminal** [Freika/dawarich#214]
The only way I can see in the app to delete points is to select them on the Points screen and hit Delete. I imported a GPX file with ~5000 points in, and unfortunately I had to restart the server while it was importing (because it spiked the CPU and made all services on the host, including ssh, inaccessible). So now I have an incomplete import of that GPX file -- I'd like to clear it out and reimport, but I'd have to perform 100 deletes (50 per page) to get rid of it all first.

The application needs the option to delete an import (and all the points connected to it) and/or a track (the container for points in a GPX file)

**Comment by Freika** [comment]
Hi @tyrrminal! Click on the name of an import in the imports list, then click "Destroy" and confirm, it will delete the import and all points associated to it.

**Comment by tyrrminal** [comment]
Awesome, that works for me. Can't believe I didn't think to click on the underlined import filename
