### ISSUE TITLE
Feature Request: Distance Units preference

### ISSUE THREAD

**Issue by tyrrminal** [Freika/dawarich#216]
Distances are displayed in the application in kilometers both in the summary and on the map tooltips. It would be nice to have a user-specific preference to display distances in imperial units instead.

**Comment by Freika** [comment]
It will be released [soon ](https://vas3k.club/post/25557/):)

**Comment by Freika** [comment]
Released in 0.13.3

**Comment by hartmark** [comment]
How do I select the unit preference? I'm getting imperial units and want to use metric. I'm running in docker.

**Comment by Freika** [comment]
@hartmark it's in 0.13.3 release info: https://github.com/Freika/dawarich/releases/tag/0.13.3

I'll add it to the doc soon
