### ISSUE TITLE
Running Immich Import isn't pulling in all dates

### ISSUE THREAD

**Issue by ttufts** [Freika/dawarich#220]
**Describe the bug**
I have 776GB of photos in Immich, up to yesterday (9/2/2024). Photos should almost all have location/date metadata. Importing Immich data into Dawarich seems to only be getting location points up to 2023, there is no data for 2024 showing in Dawarich after import. 

**Version**
0.12.2

**To Reproduce**
1. Install new Dawarich
2. Link to self hosted Immich + API Key
3. Click immich import button in Imports
4. Wait a long time for import
5. Missing 2024 data

**Expected behavior**
Import locations/dates from all photos in immich

**Comment by ttufts** [comment]
Looking through my imports list I noticed this:

[immich-geodata-<REDACTED>-from-2009-08-01-to-2023-12-31.json](https://<redacted>/imports/1) (immich_api)

Seems like the data was only imported from 2009-2023?

**Comment by ttufts** [comment]
https://github.com/Freika/dawarich/blob/d72430b5bed249cf634c2434fbca94372d6018e4/app/services/immich/import_geodata.rb#L37

Looks like you're using the memory-lane API of immich and looping over every day of the year. This will get all photos from each date in question all the way back in time. But it won't get photos from the current year, only up to 1 year back from that each date. 

Might need to also retrieve photo info for every day of the current year as well to get all data.

**Comment by ttufts** [comment]
Looks like you can use the timeline API instead of the memory-lane API for the current year. 

`api/timeline/bucket?isArchived=false&size=DAY&timeBucket=2024-09-01T00%3A00%3A00.000Z`

This works for getting 9/1/2024 just 1 day. 

You can also use size=MONTH to get the full month, so you could actually simplify your Immich import by searching 30 years back 12 times (once per month) == 360 queries. Which is better than searching every day (365) and pulling the data from each photo for each day from memory-lane. 

Obviously only a slight difference, but you'll get current year as well instead of relying on memory-lane and missing out on the current year.

**Comment by narucx** [comment]
![image](https://github.com/user-attachments/assets/c6870ec9-f462-41e9-852f-a0d7a2de29b1)
just noticed the same thing its only getting points until end 2023

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.13.5

**Comment by ttufts** [comment]
Going to log another ticket for this, but I seem to be having an issue with parsing immich data with this new update.
