### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by hunter-gatherer8** [Freika/dawarich#229]
**Describe the bug**
Following instructions in [the docs](https://github.com/Freika/dawarich/blob/master/docs/How_to_install_Dawarich_using_Docker.md) does not result in the app on port 3000 up and running.

It never fails for good, so I'm arriving at the conclusion it's broken only because after a while I'm seeing all the same messages in the log, and there are some errors (like `undefined method 'update!'`, even though I don't know if this is the culprit). So I left it running for some 15 minutes to capture the logs, and here's the result: [logs2.log](https://github.com/user-attachments/files/16900827/logs2.log) (easier to read with `less -R`).

**Version**
`docker-compose.yml` is copied from the master branch at the [latest commit](https://github.com/Freika/dawarich/commit/52f9a64716cea5b0e8dc29b0624d0461dfcb0633). It is not the first run, but I made sure to delete the old image and run `docker pull freikin/dawarich` again to be sure that it isn't some cached older version.

(Logs are from docker version 24.0.7, but I ran it with 27.2.0 later and the problem holds, so that should be irrelevant.)

**To Reproduce**
Just follow [the docs](https://github.com/Freika/dawarich/blob/master/docs/How_to_install_Dawarich_using_Docker.md).

**Expected behavior**
1. I expect following instructions in [the docs](https://github.com/Freika/dawarich/blob/master/docs/How_to_install_Dawarich_using_Docker.md) to result in a running app
2. If it fails for any reason it would be better for it to fail for good, not to be stuck in an infinite loop, so there would be no doubt if waiting for 5 more minutes somehow might solve the problem

**Comment by Freika** [comment]
This should be fixed in [0.13.4](https://github.com/Freika/dawarich/releases/tag/0.13.4)
