### ISSUE TITLE
RuntimeError: failed to get urandom on Synology DS916+ / DSM 7.2

### ISSUE THREAD

**Issue by saschazepter** [Freika/dawarich#233]
**Describe the bug**
DaWarIch on Synology DS916+ with DSM 7.2.1-69057 Update 5 is giving a "RuntimeError: failed to get urandom" upon import of (at least GeoJSON and GPX) files.

**Version**
0.13.4

**To Reproduce**
1. Go to "Imports"
2. Click on "New import"
3. Select GPX
4. Select file
5. Click "Create import"

**Expected behavior**
The import should run through and be reported as import.

**Screenshots**
None

**Logs**
See attached log file: [dawarich_app.log](https://github.com/user-attachments/files/16918683/dawarich_app.log)

**Additional context**
None

**Comment by saschazepter** [comment]
Hacked it by using the attached docker-compose.yml as well as the attached securerandom.rb file.

See:
[docker-compose.yml](https://github.com/user-attachments/files/16922379/docker-compose.yml.txt)
[securerandom.rb](https://github.com/user-attachments/files/16922380/securerandom.rb.txt)

**Comment by blakeusblade** [comment]
https://github.com/maybe-finance/maybe/discussions/1554#discussioncomment-12929275
