### ISSUE TITLE
After new immich import update, parsing seems to be failing

### ISSUE THREAD

**Issue by ttufts** [Freika/dawarich#236]
**Describe the bug**
Attempting to import immich data with version 0.13.5

**Version**
0.13.5

**To Reproduce**
1. Run Immich Import
2. Look at dawarich_sidekiq logs
3. See error

**Expected behavior**
Import Immich data up to current date

**Screenshots**

**Logs**
```
E, [2024-09-09T01:46:19.270937 #90] ERROR -- : Error performing ImportImmichGeodataJob (Job ID: d2d72ab0-1ecb-4ccb-8ded-5543de8d37be) from Sidekiq(imports) in 83820.73ms: TypeError (no implicit conversion of String into Integer):
/var/app/app/services/immich/import_geodata.rb:48:in `dig'
/var/app/app/services/immich/import_geodata.rb:48:in `valid?'
/var/app/app/services/immich/import_geodata.rb:56:in `block in parse_immich_data'
/var/app/app/services/immich/import_geodata.rb:54:in `map'
/var/app/app/services/immich/import_geodata.rb:54:in `parse_immich_data'
/var/app/app/services/immich/import_geodata.rb:17:in `call'
/var/app/app/jobs/import_immich_geodata_job.rb:9:in `perform'
```

**Additional context**

**Comment by chenrik** [comment]
I have the same error:
2024-09-09T19:55:31.458Z pid=78 tid=1g02 WARN: TypeError: no implicit conversion of String into Integer
2024-09-09T19:55:31.459Z pid=78 tid=1g02 WARN: app/services/immich/import_geodata.rb:48:in `dig'

Complete log:
[_dawarich_sidekiq_logs.txt](https://github.com/user-attachments/files/16936138/_dawarich_sidekiq_logs.txt)

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.13.6, can you check? I was able to successfully import data from Immich

**Comment by ttufts** [comment]
Looks like it's working. Points are loading in now.

**Comment by Freika** [comment]
Awesome!
