### ISSUE TITLE
Misgenerated assets for production environment related to site.webmanifest

### ISSUE THREAD

**Issue by alexbarcelo** [Freika/dawarich#242]
**Describe the bug**

When trying to achieve a "production" build (i.e. issuing a `bundle exec rake assets:precompile`) the resulting assets folder contains a `site.webmanifest-*.erb{.gz}` which is bogus, and the website fails complaining about this file.

**Version**

Tested on 0.12.x and also latest 0.13.5

**To Reproduce**

Take the docker, run `bundle exec rake assets:precompile` and then start the server in production environment (i.e. `RAILS_ENV=production`).

The website will not work and the error will be shown.

**Expected behavior**

A production environment with a previous `rake assets:precompile` should work and be the road to "production"-ish environment.

**Screenshots**

N/A

**Logs**

```
[c8c1d5693339e02edaf0d779d9f5caaa] Sprockets::Rails::Helper::AssetNotFound (The asset "favicon/site.webmanifest" is not present in the asset pipeline.
```

**Additional context**

Not a Rails expert, but looking online seems to be related to Sprockets 4.0 but somewhat addressed in Sprockets 4.1 according to an [issue on the RealFavIconGenerator library](https://github.com/RealFaviconGenerator/rails_real_favicon/issues/46).

The file `config/initializers/web_app_manifest.rb` seems to be no longer needed (if it is ok to update to 4.1) according to [this](https://github.com/RealFaviconGenerator/realfavicongenerator/issues/497#issuecomment-1945971294). I don't know if it is also needed to add an extra line in manifest.js as detailed by the [following comment](https://github.com/RealFaviconGenerator/realfavicongenerator/issues/497#issuecomment-2143593497) (the current manifest.js does not contain the site.webmanifest line).

**Comment by Freika** [comment]
In its current form, Dawarich is not meant to be run in `production mode`. It will make it harder to debug remote bugs in conditions of a self-hosted application, hence, makes little to no sense. Please, use `development` mode.
