### ISSUE TITLE
[feature] GPSLogger Integration

### ISSUE THREAD

**Issue by r3nor** [Freika/dawarich#244]
Hi, there's an efficient and lightweight GPS Logger app named [GPSLogger](https://github.com/mendhak/gpslogger). It allows setting up an endpoint URL to send location updates, it is possible to set up Parameters, HTTP Body, headers, method, etc. I am wondering if it'd be possible to integrate GPSLogger, into dawarich, since I find it better than OwnTracks for the use case.

Thanks in advance, and thanks for building dawarich!

**Comment by Freika** [comment]
@r3nor can you show an example of how GPSLogger's payload look like? is it customizable?

**Comment by saschazepter** [comment]
It's actually in your FAQ (https://dawarich.app/docs/tutorials/track-your-location#gps-logger) and in the discussions here: https://github.com/Freika/dawarich/discussions/118 ...

**Comment by Freika** [comment]
@saschazepter I guess weekend hit me hard :D

@r3nor it's already supported, yay!

**Comment by r3nor** [comment]
oh woah, didn't find that. that's awesome. Thank you, @Freika and @saschazepter !

**Comment by r3nor** [comment]
Maybe the README.md [Usage](https://github.com/Freika/dawarich#usage) section should be updated and link to that page of the docs?

**Comment by r3nor** [comment]
I wanted to mention that [GPSLogger section in the docs](https://dawarich.app/docs/tutorials/track-your-location#gps-logger) has the text repeated twice. I was looking for the documentation repo, but I'm not able to find it to make a PR. Also, it would be good to link to [GPSLogger.app](https://gpslogger.app/) website.

**Comment by Freika** [comment]
@r3nor fixed, thank you
