### ISSUE TITLE
Stadia map tiles require authentication

### ISSUE THREAD

**Issue by sunstep** [Freika/dawarich#251]
**Describe the bug**
The newly added map tiles of stadia don't work, and require an api key for it to work. On Dawarich version 0.14.0

![image](https://github.com/user-attachments/assets/5937c634-06aa-4c0e-8916-27c395be7b53)

![image](https://github.com/user-attachments/assets/a7c9e8d6-634f-4c6b-acbe-b9d312fa6845)

**Comment by vinovod** [comment]
Yep, the same issue.

**Comment by jpbaril** [comment]
I created a free stadiamaps account, created a property with my domain, and then it worked.

**Comment by Freika** [comment]
@jpbaril can you share how you did that? I'm currently more inclined to disable map layers from Stadia for now

**Comment by jpbaril** [comment]
1. https://client.stadiamaps.com/signup/
2. https://client.stadiamaps.com/dashboard/#/property/create
3. "Add domain"
4. Enter domain used for DaWarIch. I entered my top-level domain name and checked "Allow All Subdomains".

Maybe I'm wrong and it's just chance, but after doing that Stadiamaps worked.

**Comment by Freika** [comment]
@jpbaril thanks! I removed Stadia layers today in 0.14.5, though, so you might need to change yours to something else... But I see how this causes an inconvenience for other people who might have done the same, so I hope I'll figure something out.
