### ISSUE TITLE
Getting error 401 while trying to publish from OwnTracks

### ISSUE THREAD

**Issue by devgru** [Freika/dawarich#256]
**Describe the bug**
OwnTracks fails to publish tracks to a fresh installation of `dawarich`.

**Version**
0.13.5

**To Reproduce**
1. Run `dawarich` via `docker-compose`
2. Create an API key
3. Copy URL to OwnTracks
4. Click 'Publish'

**Expected behavior**
Data starts pouring into `dawarich`.

**Logs**
```
dawarich_app        | 07:45:43 web.1  | D, [2024-09-17T07:45:43.526199 #81] DEBUG -- :   User Load (1.5ms)  SELECT "users".* FROM "users" WHERE "users"."api_key" = $1 LIMIT $2  [["api_key", "[FILTERED]"], ["LIMIT", 1]]
dawarich_app        | 07:45:43 web.1  | D, [2024-09-17T07:45:43.527456 #81] DEBUG -- :   ↳ app/controllers/api_controller.rb:16:in `current_api_user'
dawarich_app        | 07:45:43 web.1  | I, [2024-09-17T07:45:43.533137 #81]  INFO -- : {"method":"POST","path":"/api/v1/owntracks/points","format":"*/*","controller":"Api::V1::Owntracks::PointsController","action":"create","status":401,"allocations":821,"duration":14.59,"view":0.0,"db":1.4}
```

**Comment by quentinClaudel** [comment]
I have the same issue and cannot connect to the UI anymore.

**Comment by Freika** [comment]
Nothing related to authentication was changed in the last 2 months at least. You can use Console to make sure you're using correct api key, and change user password there: https://dawarich.app/docs/FAQ#how-to-enter-dawarich-console

>I have the same issue and cannot connect to the UI anymore.

I'm sorry, its not detailed enough to suggest a solution.

**Comment by auer1329** [comment]
I am getting the same error. It does not work without a userID, setting it to the email or to the id "1" also doesn't work. Maybe there is something missing in the documentation? 

https://picsur.sciecne.org/i/f05b1210-d1d9-4e79-9a8f-7c7a8753bb81.jpg

**Comment by auer1329** [comment]
For me it worked with the following settings in OwnTracks on iOS:

TrackerID: CA
DeviceID: christophsiphone5pro
userID: christophauer
Authentication: off
Password: empty (off)
Secret encryption key: empty
URL: https://https://dawarich.domain.tld/api/v1/owntracks/points?api_key=asdfghjklqwertzuiopyxcvbnm

**Comment by Freika** [comment]
@devgru @auer1329 is there a chance you have a `DATABASE_NAME` value in your env variables set to something other than `dawarich_developemnt`? In one of recent releases there was a fix that allowed using custom database name, so if you had this variable value set to something other than `dawarich_development`, after that update Dawarich would actually consider it and create new database with that name, effectively stopping using the `dawarich_development` one.

If that's the case, try to change your `DATABASE_NAME` value to `dawarich_development` and let me know if it helped.

**Comment by auer1329** [comment]
@Freika Yes, I changed the `DATABASE_NAME` value to `dawarich` in the initial setup, but it's working fine with the setup I posted above

**Comment by cpetzel** [comment]
I am seeing this same error with overland... 

I have my DATABASE_NAME set to `dawarich_development`


```
07:51:03 web.1  | D, [2024-12-17T07:51:03.181474 #104] DEBUG -- :   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."api_key" IS NULL LIMIT $1  [["LIMIT", 1]]

07:51:03 web.1  | D, [2024-12-17T07:51:03.182771 #104] DEBUG -- :   ↳ app/controllers/api_controller.rb:16:in `current_api_user'

07:51:03 web.1  | I, [2024-12-17T07:51:03.183651 #104]  INFO -- : {"method":"POST","path":"/api/v1/overland/batches","format":"*/*","controller":"Api::V1::Overland::BatchesController","action":"create","status":401,"allocations":830,"duration":4.77,"view":0.0,"db":0.52}

```

I tried creating a new API token from my account settings page and using that one, and it still doesn't work.

**Comment by cpetzel** [comment]
I was trying different things, and I think I managed to fix it... 
In Overland, I was using the separate input fields for url and api token... 
I decided to use JUST the url by appending my api_token as a QP, then it worked. 

Seems to be an issue with Overland.

**Comment by Freika** [comment]
@cpetzel The API key is not supposed to go to a separate field of Overland (as of now, at least), so yes, provide it as part of the URL
