### ISSUE TITLE
Keep dates after deleting entries

### ISSUE THREAD

**Issue by ChoosenMEME** [Freika/dawarich#261]
**Describe the bug**
The selected date span is reset every time i delete entrys.

**Version**
0.14.1

**To Reproduce**
1. Go to 'Points'
2. Change the date fields 
3. Select old entrys and delete them

**Expected behavior**
The selected Date stays and i can delete more wrong entrys.

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.14.5
