### ISSUE TITLE
Visits Map Never Loads

### ISSUE THREAD

**Issue by Svagtlys** [Freika/dawarich#262]
When accessing the Visits tab to confirm or decline suggested places, the map never loads when you select Map to check what the place is.

Dawarich 0.14.1, run in Docker

**To Reproduce**
1. Log into your Dawarich instace
2. Click on Visits at the top
3. Hover over one of the suggested or confirmed places
4. Click the Map button next to the place name
5. See that map stays blank

**Expected behavior**
I would expect that the map would be visible like it is on the main tab.

**Screenshots**
![image](https://github.com/user-attachments/assets/cb9a91ae-41e2-420e-8fc5-5c8e00f72534)

**Logs**
Clicking the button to load the map does not seem to change the logs at all (doing a before and after comparison of the logs showed no changes when the button was clicked)

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.14.5
