### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by r3nor** [Freika/dawarich#282]
I would like to reset the password for an account, however there's no specification of how to configure SMTP for emails on any page of the docs, nor there is any instructions on how to do that from the CLI.

I see in the database there is the hashed password, I could replace that but I assue it is also salted. I also see a password reset token, I tried to use that one with `https://dawarich.example.com/users/password/edit?reset_password_token=2f79a59eb4a608078aff7c6843a1a9d528b21cc7a1a4ebc53b1db1c55836b89c` but it says the refresh token is not valid, so I assue I need the one from the database...

Any help?

**Comment by r3nor** [comment]
I just processed the password reset request with the `dawarich_app` logs open, and I see that the mail body is printed there. This solves my issue for now.

**Comment by Freika** [comment]
This one might be also useful for password reset: https://github.com/Freika/dawarich/discussions/265#discussioncomment-10717314
