### ISSUE TITLE
Install Dawarich yesterday and it's very extremely inaccurate

### ISSUE THREAD

**Issue by Danielson89** [Freika/dawarich#287]
![image](https://github.com/user-attachments/assets/dd64878e-d800-4646-a840-f5577602db4c)

It's also predicted my October,  November and December tracks.  It's also said I've done 255,000km since yesterday. Good effort considering.

**Comment by Danielson89** [comment]
![image](https://github.com/user-attachments/assets/eedef391-424b-4234-b188-7927ce234a98)

**Comment by Freika** [comment]
Hi! Dawarich doesn't predict anything but rather works based on provided data :) Can you send me the file you have imported to Dawarich? Link to discord server is in readme

**Comment by Danielson89** [comment]
I'm happy to send you the Google Timeline file I imported.  I lost 10 years worth of Timeline data.  So that data you are seeing if from 24th June 2024 to earlier this week.

**Comment by Freika** [comment]
Ping me when you'll send the file

**Comment by Freika** [comment]
@Danielson89 I think your problem might be related to https://github.com/Freika/dawarich/issues/291. This one was fixed in 0.14.6. Can you please update your Dawarich instance, delete your import on the Imports page, and then try to upload your json file again? Let me know if the outcome changed.

**Comment by Danielson89** [comment]
> @Danielson89 I think your problem might be related to #291. This one was fixed in 0.14.6. Can you please update your Dawarich instance, delete your import on the Imports page, and then try to upload your json file again? Let me know if the outcome changed.

Oooo,  This might sound silly and apologies for this,  How do I upgrade?  I'm only very new to this awesome tool :) and thank you for all your time making this and creating a master piece.

**Comment by Freika** [comment]
@Danielson89 depends on how you have installed it. In general case, it means entering `docker pull` command

**Comment by Danielson89** [comment]
> @Danielson89 depends on how you have installed it. In general case, it means entering `docker pull` command

Ah yep it will be a docker pull as that's how I'm running it

**Comment by Danielson89** [comment]
> @Danielson89 depends on how you have installed it. In general case, it means entering `docker pull` command

Ended up rebuilding the server,  figured out the docker pull name/project and the server just died lol

**Comment by Danielson89** [comment]
That has 100% solved the issue,  upgrading to 0.14.6,  locations are 100% accurate and looking beautiful. 

Thank you very much for providing an amazing product to replace Google Timeline

**Comment by Danielson89** [comment]
This is soo cool,  thank you very much @Freika - I'm so sad I lost 10 years worth of tracking data with Google Timeline.
