### ISSUE TITLE
Bring back point ids in the API

### ISSUE THREAD

**Issue by sunstep** [Freika/dawarich#289]
V0.14.5

In a recent update, point data was reduced in the API, which is a good thing, but one important property was removed. The point ID. This should be brought back. It makes it easier to target specific points. And if you want to delete points, the ID key is actually necessary, so it might be a good idea to display the ID of each point when obtaining them. There is currently no way to see what the ID of a point is.

**Comment by Freika** [comment]
Done in 0.14.6
