### ISSUE TITLE
Google location-history.json incorrect dates

### ISSUE THREAD

**Issue by Kombuchelada** [Freika/dawarich#291]
**Describe the bug**
I just started a new dawarich instance and imported my _location-history.json_ from my Google Maps app. The locations all seem to be correct, but the dates are very incorrect, resulting in some ridiculous distance calculations.

**Version**
0.14.5

**To Reproduce**
1. Spin up a brand new Dawarich
2. Import my _location-history.json_
3. Observe some points are correct, but the time is incorrect

**Expected behavior**
All points are placed at the correct time.

**Screenshots**
This is the screenshot from my September 2024 data, showing that I went to Denver (and lets focus on Denver International Airport for a specific point), but I did not. I have been to Denver a few times, but not on the dates that Dawarich sees.
<img width="1430" alt="Screenshot 2024-09-29 at 9 09 56 AM" src="https://github.com/user-attachments/assets/490999d0-425c-483a-80c5-7383b0291944">

I searched my _location-history.json_ for the coordinates it sees at Denver International Airport and they do show up, but the points in my _location-history.json_ file are correct and they do not match the dates that Dawarich has for those coordinates.

This is just one example. My location history goes back to 2013 and all of the Dawarich data is wildly inaccurate.

**Logs**
I can share logs of the import here if they will help, but I'm not willing to post my entire location history in the github issue. I am happy to collaborate privately to help if possible (I'm a dev too, but I know nothing about ruby).

**Additional context**
Thanks for all of the hard work you've done on this awesome project. I'm really excited to get off Google Maps and use Dawarich!

**Comment by Kombuchelada** [comment]
Or, here's one for you, @Freika 😉

<img width="1463" alt="image" src="https://github.com/user-attachments/assets/4faa1d37-0070-470c-9988-7d68b71b4a3b">


This seems to imply I was in Frankfurt on September 27, but I was actually in Frankfurt on June 12, as the _location-history.json_ shows.

**Comment by Freika** [comment]
@Kombuchelada you can send me the json file in discord private messages, so I could debug the issue. The link to discord server is in the readme

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.14.6

**Comment by Danielson89** [comment]
I can confirm that 0.14.6 fixes this issue,  It's bl--dy awesome!!!
