### ISSUE TITLE
Tracks disappear if the map is scrolled around the Earth

### ISSUE THREAD

**Issue by Cyberax** [Freika/dawarich#299]
If you zoom out on the map to the whole Earth level, and then drag the map left or right until you return to your starting location, then all the tracks disappear. This tripped me when I tried to find my tracks from a visit to China by scrolling the map to the west of my location and crossing the dateline.

Suggested fix:
https://leafletjs.com/reference.html#crs - looks like you need to disable the `infinite` coordinate space and set the wrapLng/wrapLat pairs.

**Screenshots**

https://www.loom.com/share/98c4da85a8f440d691cffbc3e8141741

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.15.5
