### ISSUE TITLE
Reverse Geocoding no longer works starting with 0.14.7

### ISSUE THREAD

**Issue by chrisl8** [Freika/dawarich#300]
I'm getting "RuntimeError" on every geocoding attempt now:

```
dawarich-sidekiq  | 2024-10-03T00:11:55.505Z pid=99 tid=i9z class=ReverseGeocodingJob jid=8b2afe62221cfe46b3f7242a elapsed=0.197 INFO: fail
dawarich-sidekiq  | 2024-10-03T00:11:55.508Z pid=99 tid=i9z WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"reverse_geocoding","wrapped":"ReverseGeocodingJob","args":[{"job_class":"ReverseGeocodingJob","job_id":"22a4df36-0b42-49a6-9167-03140dd86276","provider_job_id":null,"queue_name":"reverse_geocoding","priority":null,"arguments":["Point",4785099],"executions":0,"exception_executions":{},"locale":"en","timezone":"America/Chicago","enqueued_at":"2024-10-03T00:11:35.711141708Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"8b2afe62221cfe46b3f7242a","created_at":1727914295.7112067,"enqueued_at":1727914315.3080666,"error_message":"","error_class":"RuntimeError","failed_at":1727914295.800561,"retry_count":0}}
dawarich-sidekiq  | 2024-10-03T00:11:55.508Z pid=99 tid=i9z WARN: RuntimeError:
dawarich-sidekiq  | 2024-10-03T00:11:55.511Z pid=99 tid=i9z WARN: app/services/reverse_geocoding/points/fetch_data.rb:15:in `call'
dawarich-sidekiq  | app/jobs/reverse_geocoding_job.rb:9:in `perform'
```

I believe it is caused by this:
https://github.com/Freika/dawarich/commit/6aaab424feb87afc77cf5142165ef8c81ae43eca

Removing `config/initializers/00_monkey_patching.rb` and restarting my containers fixes the issue.

It is a shame, as I was looking forward to trying to integrate photon in my compose file if HTTPS wasn't required, but it doesn't appear to work.

**Comment by Freika** [comment]
I guess it's not as easy as I thought :) Will disable it for now with the next release.

**Comment by chrisl8** [comment]
Too bad there is not more error information given. It is impossible to tell from the small output what is going wrong.

It seems like maybe the patch is happening too late in the process and something has already run to set other values.

I also tried to fork the Geocoder repo, edit it and point Ruby at it, but that didn't work either, it just complains that the package hasn't been installed after installing it which is apparently a common issue with the Ruby bundler that has no solution.

**Comment by Freika** [comment]
Fixed in 0.15.0

**Comment by chrisl8** [comment]
@Freika  https://github.com/alexreisner/geocoder/pull/1664

**Comment by Freika** [comment]
@chrisl8 wow that's proactive! Thank you so much! I'll update the geocoder library in the next release 🔥🔥🔥

**Comment by chrisl8** [comment]
@Freika  It works! Thanks so much for pulling in the static library version!

FYI: I set `PHOTON_API_HOST` to `photon:2322`
The port on the end seems to be the "secret sauce" to make it use HTTP instead of HTTPS successfully.

It is nice to just hide the photon container inside my Dawarich setup now, and it _feels like_ it is faster, although it probably isn't.
