### ISSUE TITLE
All Records.json imports fail after update to 0.15.0

### ISSUE THREAD

**Issue by Tazmanian79** [Freika/dawarich#303]
**Describe the bug**
Im currently importing my Google Location history (Record.json)  I was already busy for more than a week and had +- 1.900.000 points to go.

This morning I have upgraded to version 0.15.0
Importing resumes but I see that all imports fail.

![Schermafbeelding 2024-10-04 142845](https://github.com/user-attachments/assets/0b1bc2a9-8340-4d5a-9a22-ddabb94b8038)

Did 0.15.0 break the Record.json import?

**Comment by Freika** [comment]
I just started my own import of Records.json and it seems to be working good:

<img width="1242" alt="изображение" src="https://github.com/user-attachments/assets/55e10611-8912-411b-8286-b8a6f32e5f3e">

Also, no code related to the import of Records.json was changed in recent releases IIRC.

I suggest you to ensure that this is import jobs were failing and not reverse geocoding ones, and if these are indeed importing ones, feel free to send me your file in discord and I'll have a look at your problem

**Comment by Tazmanian79** [comment]
I have send you on Discord ;-)

**Comment by Freika** [comment]
Double checked: Records.json are being imported as expected, closing this for now
