### ISSUE TITLE
Page not responsive

### ISSUE THREAD

**Issue by Coysh** [Freika/dawarich#313]
**Describe the bug**
I have lots of points.. Probably over 100,000 going back 10 years.
Would love to be able to render these points on a map, either as a heatmap or points - but anything more than a few years renders the maps page unresponsive.

**Version**
0.0.0

**To Reproduce**
1. Go to Map
2. Click on Start date
3. 3. Set to more than a few years

**Expected behavior**
Show all points on map

**Screenshots**

**Logs**
If applicable, add logs from containers `dawarich_app` and `dawarich_sidekiq` to help explain your problem.

**Additional context**

**Comment by Svagtlys** [comment]
Just wanted to add that I have 189k points (98k geocoded) over the last 5 years, and while Ruby does take a whole gb of memory on the host server, and Firefox momentarily says that the page is unresponsive, the page loads after 30ish seconds with all data shown.

You may need to add more info in order to have your bug recreated? E.g. what browser, the DaWarIch logs, your server specs, etc

**Comment by Freika** [comment]
This is a known issue, browsers are having problems rendering huge amounts of points. I hope to improve it in the future.

**Comment by Coysh** [comment]
> Just wanted to add that I have 189k points (98k geocoded) over the last 5 years, and while Ruby does take a whole gb of memory on the host server, and Firefox momentarily says that the page is unresponsive, the page loads after 30ish seconds with all data shown.
> 
> You may need to add more info in order to have your bug recreated? E.g. what browser, the DaWarIch logs, your server specs, etc

In answer to the specs. I'm on a Macbook Pro M1 - using Chrome, but also experienced the issue in Firefox and Safari.

**Comment by Freika** [comment]
Release [0.15.8](https://github.com/Freika/dawarich/releases/tag/0.15.8) introduces "Simplified" mode of points rendering. When enabled, points that are closer to each other than 50 meters or 20 seconds, will not be rendered, improving the map performance. Let me know if you'll encounter any issues with that or if it works good for you

**Comment by Freika** [comment]
@Coysh I'm closing this, let me know if you're still experiencing the issue and we'll reopen it.

**Comment by alternativesurfer** [comment]
This is still happening to me, except it occurs with a date range of only a few weeks.
I can't even dream of viewing an entire year (or months).

I have it on simplified mode already.

**Comment by Freika** [comment]
@alternativesurfer what version you're on? In 0.22.3 I introduced major performance improvements to the map
