### ISSUE TITLE
SSL certificate PEM placement

### ISSUE THREAD

**Issue by bwermes** [Freika/dawarich#316]
**Describe the bug**
Creating a Dawarich instance with SSL cert & HTTPS

**Version**
Latest

**To Reproduce**
Documentation provides reference to hosting the application with HTTPS (ENV VAR: APPLICATION_PROTOCOL)
However there is no documentation on where to place the PEM. 

**Additional context**
Can you provide some information on where to place the PEM or provide additional documentation?

**Comment by Freika** [comment]
This question is not related to Dawarich but rather to the reverse proxy of your choice.
