### ISSUE TITLE
Password / Email not updated

### ISSUE THREAD

**Issue by chr-ftw** [Freika/dawarich#317]
**Describe the bug**
Password is NOT changed, no new login required after changing account data.
Could not login again out after changing email. (Did not reproduce, I assume I tried the default user and password). 

**Version**
0.15.3

**To Reproduce**
1. Login with user@domain.com / password
2. Click on Account -> Settings
3. Change/enter email/password
4. Enter current password
5. Press "update"

**Expected behavior**
User and / or password updated. Possibly new login required.

**Comment by Tazmanian79** [comment]
I have done the same earlier this week and the password en username changed as expected.
Probably something wrong at your end.

**Comment by Freika** [comment]
Couldn't reproduce. You can still change your password or email using Console: https://dawarich.app/docs/FAQ#how-to-update-users-password

**Comment by woessmich** [comment]
@chr-ftw Maybe you did not enter the previous password.
I experienced the same and thought, things have changed, but they were not.

@Freika Maybe there should be some kind of message notifying the user that nothing was changed.

**Comment by nicolasshu** [comment]
One thing I found is that my issue was not that the password was unchanged, it was that I couldn't login via HTTPS. See #106. Perhaps this was another problem
