### ISSUE TITLE
Import description from owntracks no longer valid

### ISSUE THREAD

**Issue by chr-ftw** [Freika/dawarich#318]
There is no longer a download button in the topright corner of owntracks frontend.
See https://github.com/owntracks/frontend/issues/122

See picture, also here: https://dawarich.app/docs/tutorials/import-existing-data

![dw](https://github.com/user-attachments/assets/0f4fbc0d-c59b-4ebe-87b4-8c15a53674be)

**Comment by saschazepter** [comment]
Duplicates #276.

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/pull/328, will be available in the next release
