### ISSUE TITLE
crashed on import

### ISSUE THREAD

**Issue by brjppru** [Freika/dawarich#32]
Hi! i picked up the latest version in docker and tried uploading my movement archive to the app, but it stop working :-(

```
Parameters:

{"authenticity_token"=>"[FILTERED]",
 "import"=>
  {"source"=>"google",
   "files"=>
    ["",
     #<ActionDispatch::Http::UploadedFile:0x000072f2d7342370
      @content_type="application/gzip",
      @headers="Content-Disposition: form-data; name=\"import[files][]\"; filename=\"takeout-20240507T064045Z-001.tgz\"\r\n" + "Content-Type: application/gzip\r\n",
      @original_filename="takeout-20240507T064045Z-001.tgz",
      @tempfile=#<File:/tmp/RackMultipart20240507-48-rnak5w.tgz>>]},
 "commit"=>"Create Import"}
```

**Comment by Freika** [comment]
You need to extract your zip content to a folder, on 2nd or 3rd level of this folder you'll find one called "Semantic Location History", it contains all your data split by years and months.

On the Import page, click on "Choose files" and select all the small JSON files split by month (for example, 2013_APRIL.json, 2013_MAY.json and so on) and then just hit "Import".

**Comment by brjppru** [comment]
```$ find . -name "*.json" | wc -l
     118
```

can you consider the possibility that the application would suck itself into the archive from google, check fork()bomb and if it found in it *.json similar to maps it would automatically import?

**Comment by Freika** [comment]
It might be implemented in the future, but certainly not a priority at the moment. Shouldn't be much trouble to extract the Takeout archive and upload json files you want to be imported :)
