### ISSUE TITLE
Reverse geocoding jobs are failing

### ISSUE THREAD

**Issue by andkulikov** [Freika/dawarich#320]
Thanks for this project!

I recently deployed it on my local raspberry pi and imported the lopcation history from the Gogle Phone Takeout (location-history.json). It finished succesfully and now I have 110,975 Geopoints tracked.
What doesn't work as expected is recerse geocoding. So far the dashboard is showing 6,087 Reverse geocoded points. around 700 points increase over the last full day, which is pretty slow.
I have the latest 0.15.3 deployed with the umodified [docker-compose.yml](https://github.com/Freika/dawarich/blob/master/docker-compose.yml). The only tweaks I made in them is for playing with tweaking BACKGROUND_PROCESSING_CONCURRENCY to different values, which did give any improvements to me.
I logs for dawarich_sidekiq containers I see a lot of errors like Geocoder::LookupTimeout and Geocoder::LookupTimeout. More logs are here: [_dawarich_sidekiq_logs.txt](https://github.com/user-attachments/files/17350341/_dawarich_sidekiq_logs.txt)

I am happy to debug it further, but would appreciate any guidance on what exactly I can check to help finding the root cause.

**Comment by andkulikov** [comment]
I switched to have 1 in BACKGROUND_PROCESSING_CONCURRENCY and after some time in started moving quicker, now I have 15,638 processed already. I also collected the logs where we have consecutive succesful and failed requests: 
[_dawarich_sidekiq_logs(1).txt](https://github.com/user-attachments/files/17350966/_dawarich_sidekiq_logs.1.txt)

**Comment by andkulikov** [comment]
Ok, so I am not sure what have changed, but in the end the error stopped occuring and all the backgroud jobs have finished sucessfuly. I will not be able to reproduce it anymore.

**Comment by Freika** [comment]
@andkulikov you might have been tempbanned by Nominatim for amount of requests. Ban was probably lifted and Dawarich was able to finish its job
