### ISSUE TITLE
Error response from daemon: Could not find the file /var/app/public/imports in container dawarich_app

### ISSUE THREAD

**Issue by pebblecoder5** [Freika/dawarich#326]
**Describe the bug**
Trying to follow the Tutorial to import data

Copy you Records.json to the tmp folder:
docker cp Records.json dawarich_app:/var/app/public/imports/Records.json

**Version**
0.15.3

**What console shows**
root@dawarich:~# docker cp Records.json dawarich_app:/var/app/public/imports/Records.json
Successfully copied 754kB to dawarich_app:/var/app/public/imports/Records.json
Error response from daemon: Could not find the file /var/app/public/imports in container dawarich_app

**Comment by Freika** [comment]
Addressed in [0.15.11](https://github.com/Freika/dawarich/releases/tag/0.15.11)
