### ISSUE TITLE
day/night theme

### ISSUE THREAD

**Issue by brjppru** [Freika/dawarich#33]
Hi! I picked up the latest version in the docker and it worked.

can the application detect what day mode is set in the system? i set day - i went to points stars imports menu but it resets the theme to night.

can this be fixed? thanks

**Comment by Freika** [comment]
It is planned: https://github.com/users/Freika/projects/3?pane=issue&itemId=61897970 :)

**Comment by Freika** [comment]
@brjppru released in https://github.com/Freika/dawarich/releases/tag/0.2.1
