### ISSUE TITLE
Web GUI Incorrectly Alerts Update Available

### ISSUE THREAD

**Issue by Svagtlys** [Freika/dawarich#334]
**Describe the bug**
After pulling the latest Dawarich image, the web gui still has an exclamation point next to the version number in the top left, which (at least previously) indicated that a newer version was available.

**Version**
First noticed on 0.15.3, still present on 0.15.4

**To Reproduce**
1. Pull latest image of Dawarich
2.  Run Dawarich containers
3. Open the Web GUI and log in
4. Exclamation point in the top left next to the version number

**Expected behavior**
When on the latest version, there should be no exclamation point.

**Screenshots**
![image](https://github.com/user-attachments/assets/e1affaf0-a295-4e44-a825-3d7209059327)

**Logs**
N/A

**Additional context**
N/A

**Comment by Freika** [comment]
duplicates https://github.com/Freika/dawarich/issues/238
