### ISSUE TITLE
google location import way to big... how to handle?

### ISSUE THREAD

**Issue by rantanlan** [Freika/dawarich#34]
Just discovered your awesome application since I was looking for some time now to replace googles tracking.

Unfortunately, my export is 4 GB big (yeah, I know). And the application is just crashing, understandably.
Is there any way I could split the JSON into smaller junks?
But I have no idea how to handle this. Any pointers?

okay, i saw in the other issue that only the "Semantic Location History" will be imported? so it's not build to import the "route"?

**Comment by pinionless** [comment]
Hello,
I love this app, but I also want to import the records.json with full point history.
But I am able to import only Semantic Location History files.
I tried splitting the records.json to smaller files but was not able to import.

**Comment by Freika** [comment]
@rantanlan @pinionless please take a look at this comment: https://github.com/Freika/dawarich/issues/32#issuecomment-2097955211

Later it will be added to Readme section for clarity. Thanks!

**Comment by Freika** [comment]
Here's an instruction along with video tutorial: [How to import Google Location History to Dawarich](https://github.com/Freika/dawarich/wiki/How-to-import-your-Google-Takeout-data)

**Comment by pinionless** [comment]
Well, I am looking for an app that will take my whole google location history to store it and process on its own.
I will have to try owntracks.

**Comment by Freika** [comment]
@pinionless did google location history import work for you in the end?

**Comment by rantanlan** [comment]
Semantic Location is working fine. But i guess @pinionless was looking to import the complete history like me

**Comment by Freika** [comment]
@rantanlan can you please provide a bit more context, what file is assumed to be imported when you're saying "the complete history"?

**Comment by Freika** [comment]
Ah, I've re-read the original messages.

@pinionless I'll implement importing `records.json` as well, too. Meanwhile, in my understanding, semantic location history should contain basically the very same geopoints, as in `records.json` but with more excessive data.

**Comment by Freika** [comment]
@pinionless @rantanlan implemeted in https://github.com/Freika/dawarich/releases/tag/0.2.3

**Comment by rantanlan** [comment]
With semantic you only get the major points / cities you visited.
The records.json contains ever single point recorded over time. And i wasn't able to import it due to the size I guess (4GB). Tried also to use just a little potion of it but guess i wasn't able to split/format it correctly...

**Comment by Freika** [comment]
Huh, 4GB sound like a potential problem... I'll also try to figure something out to import files of such size via cli tool or something like that.
