### ISSUE TITLE
! dawarich_sidekiq Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. 0.0s 

### ISSUE THREAD

**Issue by MrColumbo** [Freika/dawarich#342]
After the last upgrade ....up to version 15 everything was working all right but now with Version 18 the app does not even start and i get these errors:

! dawarich_sidekiq Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. 0.0s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: openat2 /sys/fs/cgroup/docker/49c8dfa93534aaa694fa2076e43be097ea1f852e51866afa58560081326c0b4a/memory.max: no such file or directory: unknown

I am using Proxmox and for sure it can be related to that. I have a backup from the LXC Container (I am using Alpine) where i can restore it and successfully start the old version.

I changed the docker compose file since there where a lot of changes before i pulled everything again and tried to start it.

Any ideas what is exactly happening here?

**Comment by MrColumbo** [comment]
After i removed those lines (twice - i first did not notice that they appear twice):

 deploy:
      resources:
        limits:
          cpus: '0.50'    # Limit CPU usage to 50% of one core
          memory: '2G'    # Limit memory usage to 2GB

....it worked again. Since I am able to limit those resources via the LXC Container i did not need that anyway

**Comment by Freika** [comment]
TIL! Thanks for posting an update!
