### ISSUE TITLE
Import fails : "no implicit conversion of String into Integer (TypeError)"

### ISSUE THREAD

**Issue by vikramwalia** [Freika/dawarich#345]
**Describe the bug**
When trying to import records exported from an iOS device is giving the following error.
" no implicit conversion of String into Integer (TypeError) "

**Version**
0.15.7

**To Reproduce**
1) Get file into docker
2) run bundle exec rake import:big_file['public/imports/location-history.json','xxxx@gmail.com']

**Expected behavior**
The import process is supposed to kick off

**Screenshots**

**Logs**
/var/app # bundle exec rake import:big_file['public/imports/location-history.json','xxxx@gmail.com']  --trace
** Invoke import:big_file (first_time)
** Invoke environment (first_time)
** Execute environment
[dotenv] Set DATABASE_PORT
[dotenv] Loaded .env.development
** Execute import:big_file
D, [2024-10-20T14:19:17.848883 #27755] DEBUG -- :   User Load (1.2ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "xxxx@gmail.com"], ["LIMIT", 1]]
D, [2024-10-20T14:19:17.849353 #27755] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:9:in `initialize'
D, [2024-10-20T14:19:17.926209 #27755] DEBUG -- :   TRANSACTION (0.3ms)  BEGIN
D, [2024-10-20T14:19:17.927170 #27755] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:26:in `create_import'
D, [2024-10-20T14:19:17.928513 #27755] DEBUG -- :   Import Create (2.6ms)  INSERT INTO "imports" ("name", "user_id", "source", "created_at", "updated_at", "raw_points", "doubles", "processed", "raw_data", "points_count") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["name", "public/imports/location-history.json"], ["user_id", 1], ["source", 2], ["created_at", "2024-10-20 14:19:17.924714"], ["updated_at", "2024-10-20 14:19:17.924714"], ["raw_points", 0], ["doubles", 0], ["processed", 0], ["raw_data", nil], ["points_count", 0]]
D, [2024-10-20T14:19:17.929261 #27755] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:26:in `create_import'
D, [2024-10-20T14:19:17.930712 #27755] DEBUG -- :   TRANSACTION (1.1ms)  COMMIT
D, [2024-10-20T14:19:17.931200 #27755] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:26:in `create_import'
D, [2024-10-20T14:19:17.931422 #27755] DEBUG -- : Importing public/imports/location-history.json for xxxx@gmail.com, file size is 29222021... This might take a while, have patience!
rake aborted!
TypeError: no implicit conversion of String into Integer (TypeError)

    json_data['locations'].each do |json|
              ^^^^^^^^^^^
/var/app/app/services/tasks/imports/google_records.rb:34:in `schedule_import_jobs'
/var/app/app/services/tasks/imports/google_records.rb:19:in `call'
/var/app/lib/tasks/import.rake:9:in `block (2 levels) in <main>'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:279:in `block in execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:279:in `each'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:279:in `execute'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:83:in `block in run'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
/var/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/var/app/vendor/bundle/ruby/3.3.0/bin/rake:25:in `load'
/var/app/vendor/bundle/ruby/3.3.0/bin/rake:25:in `<top (required)>'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/var/app/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => import:big_file
/var/app # 

**Additional context**

**Comment by Freika** [comment]
This kind of file goes to the Imports page: 
![tg_image_2823926734](https://github.com/user-attachments/assets/48fc9a58-c317-40c5-be6e-cac7cfc4af5c)

How big is your file?

**Comment by vikramwalia** [comment]
Thank you for your reply @Freika  , the file is 30 mb roughly but I do not see that UI, am I missing something  ? When I goto import and click on new import I get the process to use docker to import it all in using the commands as above.


![screenshot-2024-10-20-13 00 04-Area](https://github.com/user-attachments/assets/1cfe2654-9a40-4b69-b978-0352191da3e1)
![screenshot-2024-10-20-12 59 48-Area](https://github.com/user-attachments/assets/dee5928d-fb7c-4e2e-bc2b-b76c6739fbdb)

**Comment by vikramwalia** [comment]
Thank you @Freika  , once the process fails and I go back into imports and change the source and provide the file again. It does not do anything. Am I missing something, sorry for this but I am unclear on what the steps should look like.

![screenshot-2024-10-20-13 16 54-Area](https://github.com/user-attachments/assets/88cdcf81-6e87-4ad6-864a-1463f9c35869)
![screenshot-2024-10-20-13 17 06-Area](https://github.com/user-attachments/assets/4cdd8310-3d57-422f-ac09-3b0bbea48f85)
![screenshot-2024-10-20-13 17 30-Area](https://github.com/user-attachments/assets/b4ae2a87-68a8-4f86-9fe5-fe923ef67bab)

**Comment by Freika** [comment]
@vikramwalia you have to create a new import, not edit existing one, editing is not triggering process from scratch

**Comment by vikramwalia** [comment]
Thank you @Freika  , that was me being dumb ! I really really appreciate your help. We can mark this thread as resolved. I did not scroll down to see if the options were right underneath the docker instructions.
