### ISSUE TITLE
Deleting points or changing order removes filters on `Points` page

### ISSUE THREAD

**Issue by tomudding** [Freika/dawarich#363]
**Describe the bug**
When using the points overview to delete specific points the selected filters are removed when deleting points and/or changing the ordering.

**Version**
`0.15.11`

**To Reproduce**
1. Go to 'Points'
2. Filter on an arbitrary date
3a. Select a view points
4a. Click on 'Deleted Selected'
5a. Confirm
6a. Redirected back to 'Points' (without the previous filters)

or

1. Go to 'Points'
2. Filter on an arbitrary date
3b. Change the ordering by clicking on 'Oldest'
4b. You are now at `/points?order_by=asc` (without any other filters)

**Expected behavior**
The filters (e.g. `start_at=2000-01-01T00%3A00&end_at=2000-01-02T23%3A59%3A59`) are preserved through these operations.

**Screenshots**
N/A

**Logs**
N/A

**Additional context**
N/A

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.16.4
