### ISSUE TITLE
Exporting a .GPX files doesn't have an extension upon download

### ISSUE THREAD

**Issue by HStep20** [Freika/dawarich#377]
**Describe the bug**
When exporting and downloading a GPX file, it doesn't have the '.gpx' extension on the file. Its not a huge problem since it can be added by renaming the file to add `.gpx` to the end of it, but it'd be great if it worked natively since the GeoJson exports download with the proper .json extension.

I am using firefox, but interestingly on Microsoft Edge it downloads with a .txt extension

**Version**
Dawarich 16.2
Windows 10
Firefox is my browser of choice

**To Reproduce**
1. Open Firefox and Log in
2. Go to Points and create a GPX export
3. Download the complete export and see it doesnt have a file extension

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.16.4
