### ISSUE TITLE
Connection to redis error

### ISSUE THREAD

**Issue by Sgaina** [Freika/dawarich#382]
Stats update fails with the following notification error:
"Address not available - connect(2) for [::1]:6379 (redis://localhost:6379/1)"

Version 0.16.2

1. Go to Stats Page
2. Click on 'Update Stats'
3. After a few seconds a notification is shown reporting the following in the first line of the log:
4. "Address not available - connect(2) for [::1]:6379 (redis://localhost:6379/1)"

**Expected behavior**
Only "Stats Updated" showld be shown

Additional context:
Install is made on a ubuntu-22.04.3 clean server with docker version 24.0.5 with the following instructions:
https://dawarich.app/docs/intro#setup-your-dawarich-instance

[dawarich.log](https://github.com/user-attachments/files/17689607/dawarich.log)

**Comment by Freika** [comment]
Fixed in 0.16.3
