### ISSUE TITLE
Sikdekiq and main container restart safety

### ISSUE THREAD

**Issue by shaman007** [Freika/dawarich#397]
How safe are container restarts? I have 450 000 to reverse-geocode in the sidekiq, would they be processed if I restart my container?

**Comment by shaman007** [comment]
It's safe since everyting is in Redis

**Comment by Freika** [comment]
There was one report where a user lost their data in Sidekiq queue after the container restart, but that's not what supposed to happen and nobody else reported it. And you can restart reverse geocoding process anytime anyway.
