### ISSUE TITLE
Trip lines are cut

### ISSUE THREAD

**Issue by alangrafu** [Freika/dawarich#403]
**Describe the bug**
Points are connected by lines, but sometimes those lines are cut, as if they were 2 different trips, which doesn't make much sense, since it is the same entity traveling.

**Version**
0.16

**To Reproduce**

1. Check on some long trip
2. The lines are cut 

**Expected behavior**
Since it is the same person/device traveling, I would expect a line between each contiguous point.

**Screenshots**

This is **owntracks** UI
<img width="745" alt="image" src="https://github.com/user-attachments/assets/9cc5620f-27db-451b-9462-acc5d85fb1ab">

This is **dawarich** UI
<img width="512" alt="image" src="https://github.com/user-attachments/assets/0df5ca8f-206a-4057-9414-ec8ebda2035a">

**Logs**
N/A

**Additional context**
N/A

**Comment by Freika** [comment]
Owntracks and Dawarich are rendering routes differently. In Owntracks, all the points (literally all of them) are connected by one single polyline, while Dawarich breaks it into separate routes, based on space and time between consequent points to prevent total mess from being rendered on the map.

Here's how my own location history would look like in a single line:

![изображение](https://github.com/user-attachments/assets/ebcc1dea-8b72-4160-a06f-5d659cca9b12)

And here is the same dataset with routes split:

![изображение](https://github.com/user-attachments/assets/17a72969-fe74-455a-bc9b-be89e1b9c367)

As a user, you can change settings of how routes being drawn in the map settings, right top corner: 
<img width="296" alt="изображение" src="https://github.com/user-attachments/assets/42b95729-9ecd-458a-8840-15fb3d79ee00">

Later on, this might be changed, I have an idea of having "route" entity on the backend, and when it's implemented, I'll think about working on functionality to enable users to merge their routes and render them as a single route.

**Comment by alangrafu** [comment]
Thanks for the clarification!
