### ISSUE TITLE
Watcher stopped working

### ISSUE THREAD

**Issue by Carunga** [Freika/dawarich#420]
**Describe the bug**
GPX-Files put in the watcher directory are not imported anymore - it used to work perfectly before. No error messages in the logs, manual import of the same files works.

**Version**
16.5. but I think it started on16.3. (but not 100% sure)

**To Reproduce**
- download docker-compose.yml
- mount watched dir to host 
- copy files in watched directory

**Expected behavior**
Files should be imported

**Logs**
no meassage found

**Additional context**
there is a contradiction in the [documentation](https://dawarich.app/docs/tutorials/watcher) - the path in the docker-compose.file does not match the path in the text (but both path do not work for me).
I use a NFS-Mount in my docker-compose, but it used to work before and no change if I copy files manually inside the container (using the shell gained via docker exec ...).

What can I do to debug? I am stuck. 

Thanks for this great software, I really do enjoy it!

**Comment by AleCornella** [comment]
Same problem here using 16.8

**Comment by Freika** [comment]
I'll have a look, thank you

**Comment by Freika** [comment]
@AleCornella @Carunga I just checked locally and automatic import worked for me. Is your container `dawarich_sidekiq` running?

**Comment by Freika** [comment]
Closing this due to lack of information, feel free to reopen if the problem is still peristing
