### ISSUE TITLE
Deleting points on map: multiple alerts, doesn't update

### ISSUE THREAD

**Issue by ajpanton** [Freika/dawarich#435]
When I try to delete a point on the map, it first sends an alert to confirm the delete. Pressing OK, and immediately another identical alert pops up. Pressing OK, and a third identical alert pops up. This third is the last one - pressing OK the third time gets rid of the alerts. Well, sometimes. I've also managed to get into a state where four OK's are required.

Next issue is that the point I tried to delete is still there on the map. I can repeat the above, but the point is still there. However, refreshing the page reveals that the point is in fact deleted, it's just not updated on the map.

Now, refreshing the page (just a simple F5) solves all problems. Now, deleting a point will only send one alert, and it will disappear from the map immediately. But refreshing is the only way to get into a state that works. Clicking on a year, month, or "Search" will again get me into a state that doesn't work. I've already developed a habit of just immediately F5 whenever I open the map or change the time window.

Steps to reproduce:
1. Go to the map by clicking on something in the app (don't touch the address bar).
2. Optional: choose any time window (preferably short, as too many points makes everything slow)
3. Select to display points
4. Click on a point and try to delete it

At any stage after step 2:
3': Press F5 (or use the address bar to re-open the map)
4': There are no problems, until you repeat step 2 (or 1).

**Comment by Freika** [comment]
Fixed, feel free to reopen if this will appear again
