### ISSUE TITLE
Unable to view trips without Immich API key

### ISSUE THREAD

**Issue by mroetsc** [Freika/dawarich#451]
**Describe the bug**
I added a new trip, but do not have an Immich API key configured. When I click on the trip, I get a Rails error page (see below).

**Version**
0.18.0

**To Reproduce**
1. Create new trip (but don't have a Immich API key configured)
2. Click on the trip on the /trips page
3. Error page

**Expected behavior**
Review the trip as seen in the trip demo video from the 0.18.0 changelog.

**Screenshots**
on `dawarich.domain.tld/trips/1`
![image](https://github.com/user-attachments/assets/605e9f94-fb21-461b-9176-f284b1dc8d82)

**Logs**
```yml
dawarich_app      | 18:20:46 web.1  | I, [2024-11-28T18:20:46.152124 #116]  INFO -- : {"method":"GET","path":"/trips/1","format":"html","controller":"TripsController","action":"show","status":500,"allocations":907398,"duration":716.03,"view":0.0,"db":233.78}
dawarich_app      | 18:20:46 web.1  | F, [2024-11-28T18:20:46.153938 #116] FATAL -- :   
dawarich_app      | 18:20:46 web.1  | ArgumentError (Immich API key is missing):
dawarich_app      | 18:20:46 web.1  |   
dawarich_app      | 18:20:46 web.1  | app/services/immich/request_photos.rb:15:in `call'
dawarich_app      | 18:20:46 web.1  | app/models/trip.rb:25:in `photos'
dawarich_app      | 18:20:46 web.1  | app/controllers/trips_controller.rb:19:in `block in show'
dawarich_app      | 18:20:46 web.1  | app/controllers/trips_controller.rb:18:in `show'
```

**Comment by MeijiRestored** [comment]
I got the same issue

**Comment by pablogglz** [comment]
+1

**Comment by Freika** [comment]
Fixed in https://github.com/Freika/dawarich/releases/tag/0.18.1, thanks!
