### ISSUE TITLE
Unable to import google Records.json (user not found)

### ISSUE THREAD

**Issue by rossdargan** [Freika/dawarich#453]
**Describe the bug**
Freshly installed the app using docker compose. Copied the records.json file into the container, and executed `bundle exec rake import:big_file['tmp/imports/Records.json','user@example.com']`

Told user not found. I've logged into the app, not changed the default username/password.

**Version**
18.0 (looks like docker compose won't update to 18.2 for some reason

**To Reproduce**
1. Spin up a new instance.
2. Login to site, and go to import
3. follow the instruction for importing a google takeout file

**Expected behavior**
I'd expect the files to import

**Screenshots**
Logs are probably more helpful here.

**Logs**
This is from the console of the container
```
/var/app # bundle exec rake import:big_file['tmp/imports/Records.json','user@example.com']
[dotenv] Set DATABASE_PORT
[dotenv] Loaded .env.development
2024-11-29T15:24:50.863Z pid=1112 tid=3ig INFO: Sidekiq 7.3.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://dawarich_redis:6379/0"}
D, [2024-11-29T15:24:51.522578 #1112] DEBUG -- :   User Load (1.1ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "user@example.com"], ["LIMIT", 1]]
D, [2024-11-29T15:24:51.523098 #1112] DEBUG -- :   ↳ app/services/tasks/imports/google_records.rb:9:in `initialize'
rake aborted!
User not found
/var/app/app/services/tasks/imports/google_records.rb:13:in `call'
/var/app/lib/tasks/import.rake:9:in `block (2 levels) in <main>'
```

**Comment by tedtms** [comment]
Can you confirm that your Dawarich login's username is still `user@example.com`? The default user and the user credential example listed in the guide's command snippet might not be the same.

**Comment by rossdargan** [comment]
yes, I haven't changed it. 
![image](https://github.com/user-attachments/assets/850efb5e-af59-4993-b1be-cc5e94cfef26)
I have changed the exposed port, but I can't see how that would impact this at all.

**Comment by rossdargan** [comment]
oh ffs. I haven't changed it, but it is user@domain.com - I guess the default has changed.

**Comment by Freika** [comment]
> `bundle exec rake import:big_file['tmp/imports/Records.json','user@example.com']`

It's literally an example, you must change email to the one you have :)

And by the way, starting 0.18.2, default user email was changed to `demo@dawarich.app`
