### ISSUE TITLE
Feature Request - Ability to see your locations for the day 

### ISSUE THREAD

**Issue by Danielson89** [Freika/dawarich#457]
Like Google Timelines it has a list of locations you visited today and also the ability to edit them directly.  For example I visited McDonalds today but the locations says Poolworx so I can change that to say McDonalds?

Thanks

**Comment by Danielson89** [comment]
Other than that this tool is bloody awesome!  I never look at Google Timelines.  Infact in a few weeks time once I'm happy I'm deleting my Google account.

**Comment by Freika** [comment]
It's requested in https://github.com/Freika/dawarich/discussions/61

**Comment by Danielson89** [comment]
Yep,  Exactly what I would like,  Also I want to donate to you but it only had monthly plans.

**Comment by Danielson89** [comment]
Ignore,  found it and donated :) I know it's not a lot for your time and effort but I hope it will buy you a coffee in today's prices
