### ISSUE TITLE
Registration barring for new account.

### ISSUE THREAD

**Issue by Brodiyaga** [Freika/dawarich#46]
Greetings.
To send the traceroute to your/my server, you have to open up access to the entire internet, including the ability to register new account.

Is there any way to restrict registration to unauthorised people?

Thank you very much for the application and good luck in development.

**Comment by Freika** [comment]
There is currently no way to restrict registrations, but I'll certainly implement it in one of future releases.

**Comment by Freika** [comment]
Free registration was disabled in https://github.com/Freika/dawarich/releases/tag/0.8.1
