### ISSUE TITLE
Corrupt data? Map is broken and no GUI way to see or undo it.

### ISSUE THREAD

**Issue by rorymurtagh** [Freika/dawarich#465]
Seeing:

TypeError in MapController#index
nil can't be coerced into Float
Extracted source (around line #39):
              
    @coordinates.each_cons(2) do
      @distance += Geocoder::Calculations.distance_between(
        [_1[0], _1[1]], [_2[0], _2[1]], units: DISTANCE_UNIT
      )
    end
Rails.root: /var/app
Application Trace | Framework Trace | Full Trace
app/controllers/map_controller.rb:39:in `block in distance'
app/controllers/map_controller.rb:38:in `each'
app/controllers/map_controller.rb:38:in `each_cons'
app/controllers/map_controller.rb:38:in `distance'
app/controllers/map_controller.rb:13:in `index' 

**Version**
0.18.2

**To Reproduce**
Log in.
Default page is: <my instance>/map  and this page throws the error.

**Expected behavior**
Would expect to see a map.

**Screenshots**
Error text as above.

*

**Comment by rorymurtagh** [comment]
I had tried to upload my .gpx saves from Garmin. So definitely thousands, maybe millions.

**Comment by Freika** [comment]
@rorymurtagh I'd suggest you to update to the most recent version, there was a similar error I fixed yesterday, might solve your problem as well
