### ISSUE TITLE
Clicking "More Photos on Immich" from Trip page goes to broken URL

### ISSUE THREAD

**Issue by Mavi222** [Freika/dawarich#467]
**Describe the bug**
When clicking "More Photos on Immich" from Trip page, the URL is broken and Immich says "Not Found 404"

**Version**
0.18.2

**To Reproduce**
1. Go to 'Trip page'
2. Click on 'More Photos on Immich'
3. See error

**Expected behavior**
It should filter photos from the timespan set in the trip settings.

**Additional info**
The URL it goes to has two forward slashes instead of one, when I remove one slash it filters the photos without a problem.

http://ip:2283 **//** search?query=%(...)

these two slashes should be one.

**Comment by Freika** [comment]
@Mavi222 just remove trailing slash from the url in your settings, I'll fix it in one of the future releases

**Comment by Freika** [comment]
Fixed
