### ISSUE TITLE
Photos on Trip Detial are broken

### ISSUE THREAD

**Issue by tabacha** [Freika/dawarich#506]
**Describe the bug**
The link to the Phtos on the Main Trip Page are borken

**Version**
0.19.3

**To Reproduce**

1. Upload some images to Immich
2. Connect Immich and DaWarIch 
3. Go to Trips
4. Click on Details of one of the Trips
5. See Images not Displayed

**Expected behavior**

The Image Link should not be broken

**Screenshots**
![image](https://github.com/user-attachments/assets/dd138ce8-cbc5-47b1-994f-a471d2ddada9)

**Additional context**

The Url to the images looks like this:

https://dawarich.anders.hamburg/api/v1/photos/ef9f2771-b67a-45d5-8ce1-f9e22973ab2d/thumbnail.jpg?api_key=b74121779a1d1ecb12546e522a4f70f1

When I change this in Chrome Developer Tools to:

https://dawarich.anders.hamburg/api/v1/photos/ef9f2771-b67a-45d5-8ce1-f9e22973ab2d/thumbnail.jpg?api_key=b74121779a1d1ecb12546e522a4f70f1&source=immich

The Image is shown. 
![image](https://github.com/user-attachments/assets/d5a30cca-55eb-4139-b085-47fd28072cd7)

I guess that you need to change:

`./app/javascript/controllers/maps_controller.js`

```
const thumbnailUrl = `/api/v1/photos/${photo.id}/thumbnail.jpg?api_key=${this.apiKey}`;
```
to 
```
const thumbnailUrl = `/api/v1/photos/${photo.id}/thumbnail.jpg?api_key=${this.apiKey}&source=immich`;
```

**Comment by Freika** [comment]
Fixed in [0.19.4](https://github.com/Freika/dawarich/releases/tag/0.19.4)
