### ISSUE TITLE
Benn running for 1 week + millions of Records.json imported, but zero trips, visits, or places...

### ISSUE THREAD

**Issue by hopeseekr** [Freika/dawarich#509]
```
dawarich=# SELECT * FROM places;
 id | name | longitude | latitude | city | country | source | geodata | reverse_geocoded_at | created_at | updated_at 
----+------+-----------+----------+------+---------+--------+---------+---------------------+------------+------------
(0 rows)

dawarich=# SELECT * FROM visits;
 id | area_id | user_id | started_at | ended_at | duration | name | status | created_at | updated_at | place_id 
----+---------+---------+------------+----------+----------+------+--------+------------+------------+----------
(0 rows)

dawarich=# SELECT * FROM trips;
 id | name | started_at | ended_at | distance | user_id | created_at | updated_at 
----+------+------------+----------+----------+---------+------------+------------
(0 rows)
```

Any ideas???

I'm using the `docker compose` instance with one exception: It's running against my on-host postgresql server, running in the dawarich database. PostgreSQL v16.3.

**Comment by suth** [comment]
I was also confused why I never got suggestions for places and visits and found [this discussion](https://github.com/Freika/dawarich/discussions/298). It seems like the background job has been disabled but the UI is still visible. Trips on the other hand are something you have to create yourself.

**Comment by Freika** [comment]
https://dawarich.app/docs/features/visits-and-places

**Comment by hopeseekr** [comment]
dawarich_sidekiq  | D, [2024-12-31T00:21:29.614317 #106] DEBUG -- :   Point Update (0.5ms)  UPDATE "points" SET "city" = $1, "country" = $2, "upda
  ted_at" = $3, "geodata" = $4 WHERE "points"."id" = $5  [["city", "Bogota"], ["country", "Colombia"], ["updated_at", "2024-12-31 00:21:29.612867"],
   ["geodata", "{\"geometry\":{\"coordinates\":

[-74.04411996776741,4.69786035],\"type\":\"Point\"},\"type\":\"Feature\",\"properties\":  from Sidekiq(reverse_geocoding) enqueued at 2024-12-08T23:57:22.964222241Z with arguments: "Point", 1750874


Well, as of 2024-12-31, midnight UTC, it has gotten to June 2024, for stuff enqueued at 2024-12-08, for a process that started on 2024-12-02...

I view this as quite bad. it's the slowest compute process I've encountered since compiling X11 on my i486 35 years ago... (that took 2 1/2 weeks). So I think this is the longest-running task in my entire 43 years of life.

**Comment by hopeseekr** [comment]
I don't understand why this bug report was closed. Clearly, it's still an issue.

**Comment by Freika** [comment]
@hopeseekr please visit the page I referred to above (https://dawarich.app/docs/features/visits-and-places) and read the text, it answers your question:

> Visits and places are supposed to work in the same way as they are working in Google Maps, but as of version 0.19.3, they are not working as expected and are not recommended to use, except for the [Areas](https://dawarich.app/docs/features/areas) feature.
