### ISSUE TITLE
Distance calculation after Google import is much to high

### ISSUE THREAD

**Issue by xXZaretXx** [Freika/dawarich#53]
Hi,
i have imported my first year in dawarich from Google Maps.  Year 2013
I'm not sure wich values are normal but i get for 3 month 100.000 geopoints with a distance of 285,419,308km.
I'm sure i don't travel 70.000x around the earth ;)

**Comment by Freika** [comment]
Hi @xXZaretXx! Yeah, it's a known problem, it happens due to imperfection of importing code, certain points it parses with coordinates 0.0,0.0 and it breaks distance calculation. It will be fixed in near future :)

**Comment by xXZaretXx** [comment]
Ah ok thank you. I remain excited. Especially now that Google Maps is becoming impractical due to the data move to smartphones.

**Comment by Freika** [comment]
@xXZaretXx can I ask you to send me your 2013 year's file? You could replace your real coordinates with some fake ones (it's okay if they are all the same, while they are not 0.0,0.0 :). It will make fixing process easier for me.

Thanks!

**Comment by Freika** [comment]
With help from @xXZaretXx we managed to establish a flaw in importing process, which will be fixed in one of closest releases 🎉
