### ISSUE TITLE
Possible bug: Map draws polylines between points that shouldn't be linked

### ISSUE THREAD

**Issue by Hulabaloon** [Freika/dawarich#530]
**Describe the bug**
I'm not sure if this is a bug with how Dawarich draws polylines between points, or if there are erroneous points in the Google Maps Records.json I imported, but I have a few instances where it is drawing poylines back and forth between my home and a location that the point at home should not be linked to. It's hard to explain, but the screenshot below should show it better. For example, on this trip when I was in England for several days there should not be any points from my home in Ireland at the same time, but from the map it looks like I had flown back and forth a hundred times.

It's also inflating my total travel distance by hundreds of thousands of KMs on the stats page.

**Version**
0.19.6

**To Reproduce**
1. Go to Map Page
2. Select a certain date range

**Screenshots**

![PyKOeZd](https://github.com/user-attachments/assets/ed79e18d-0aa1-46a6-bce0-903e16c37c71)

**Comment by Beer17HWAM** [comment]
Maybe you had more devices at that time, one home and one in your pocket. Take a look at the devicetag in the file. That number is representing your device. But I still think it's not clear at all. I have the same problem when I import the "Semantic Location History" only. See: https://github.com/Freika/dawarich/issues/486

**Comment by Hulabaloon** [comment]
Oh that could be it, you're a lifesaver. It's been driving me crazy
