### ISSUE TITLE
Scratch map is ignoring MK

### ISSUE THREAD

**Issue by ajpanton** [Freika/dawarich#537]
![image](https://github.com/user-attachments/assets/58508445-10cd-4d78-a6d4-226311e84d96)
Not sure if this is even something you can do anything about, but at least reverse geocoding was able to identify the country.

**Comment by Freika** [comment]
I'd suggest to make sure the points that are tracked in Macedonia are reverse geocoded. It seems to be the problem, scratch map is working based on reverse-geocoding data in the points

**Comment by ajpanton** [comment]
How do I make sure? Isn't reverse geocoding responsible for it being to tell what country and cities I've visited, which it shows on the right?

Checking the database for those points, columns "city", "country" and "geodata" (with exact addresses) are all filled in correctly.

**Comment by Freika** [comment]
> How do I make sure? Isn't reverse geocoding responsible for it being to tell what country and cities I've visited, which it shows on the right?
> 
> Checking the database for those points, columns "city", "country" and "geodata" (with exact addresses) are all filled in correctly.

Can I ask you to send me a couple of your points there? You can remove actual coordinates

**Comment by ajpanton** [comment]
> > How do I make sure? Isn't reverse geocoding responsible for it being to tell what country and cities I've visited, which it shows on the right?
> > Checking the database for those points, columns "city", "country" and "geodata" (with exact addresses) are all filled in correctly.
> 
> Can I ask you to send me a couple of your points there? You can remove actual coordinates

Here's a collection of points. Didn't bother removing any coordinates, as it's just driving in the middle of nowhere.
[data.csv](https://github.com/user-attachments/files/18157754/data.csv)

**Comment by Freika** [comment]
Got it, will be fixed in the next release. Thanks!
