### ISSUE TITLE
Cannot load years for map

### ISSUE THREAD

**Issue by tomudding** [Freika/dawarich#558]
**Describe the bug**
The years and months in the new map menu do not load:

![image](https://github.com/user-attachments/assets/7c157cf7-3034-4c46-b5f7-4851b643996a)

**Version**
`0.20.0` and `0.20.1` on a new install but with data restored from a backup.

**To Reproduce**
1. Check out the map
2. Click on the calendar icon
3. See error

**Expected behavior**
The list of tracked years and months is populated based on the available data.

**Screenshots**
(see above)

**Logs**
There is a JS error in `maps_controller-{hash}.js`:
```
Error fetching tracked months: TypeError: yearData.year is undefined
```

This property should be defined according to

https://github.com/Freika/dawarich/blob/3554e405db5f549eaf913d4758602f04c662c580/app/models/user.rb#L69-L81

However, the actual result from the API call looks like this (when checking in the browser):
![image](https://github.com/user-attachments/assets/0e237086-6130-489f-b184-ccdfae73f848)

**Additional context**
N/A

**Comment by Freika** [comment]
@tomudding on which line of `maps_controller.js` you see the error occuring?

**Comment by tomudding** [comment]
> @tomudding on which line of `maps_controller.js` you see the error occurring?

It errors here:
https://github.com/Freika/dawarich/blob/3554e405db5f549eaf913d4758602f04c662c580/app/javascript/controllers/maps_controller.js#L1099

Full stack trace:
```
Error fetching tracked months: TypeError: yearData.year is undefined
    currentYearData [REDACTED]/assets/controllers/maps_controller-e9ea1b41353438931ff99f6af36a9257cd5ed3331cdaebeb8a18926b7ae6b507.js:1099
    fetchAndDisplayTrackedMonths [REDACTED]/assets/controllers/maps_controller-e9ea1b41353438931ff99f6af36a9257cd5ed3331cdaebeb8a18926b7ae6b507.js:1099
    onAdd [REDACTED]/assets/controllers/maps_controller-e9ea1b41353438931ff99f6af36a9257cd5ed3331cdaebeb8a18926b7ae6b507.js:1032
    addTo [REDACTED]/assets/leaflet-df8cad8209f4c881748f4a80602b1db6b35fd939bdeba37ddbd0402f3782648b.js:5
    addControl [REDACTED]/assets/leaflet-df8cad8209f4c881748f4a80602b1db6b35fd939bdeba37ddbd0402f3782648b.js:5
    toggleRightPanel [REDACTED]/assets/controllers/maps_controller-e9ea1b41353438931ff99f6af36a9257cd5ed3331cdaebeb8a18926b7ae6b507.js:1071
    connect [REDACTED]/assets/controllers/maps_controller-e9ea1b41353438931ff99f6af36a9257cd5ed3331cdaebeb8a18926b7ae6b507.js:186
    connect [REDACTED]/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js:4
    connectContextForScope [REDACTED]/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js:4
    connectModule [REDACTED]/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js:4
    connectModule [REDACTED]/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js:4
    loadDefinition [REDACTED]/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js:4
    load [REDACTED]/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js:4
    load [REDACTED]/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js:4
    register [REDACTED]/assets/stimulus.min-dd364f16ec9504dfb72672295637a1c8838773b01c0b441bd41008124c407894.js:4
    registerController [REDACTED]/assets/stimulus-loading-3576ce92b149ad5d6959438c6f291e2426c86df3b874c525b30faad51b0d96b3.js:81
    registerControllerFromPath [REDACTED]/assets/stimulus-loading-3576ce92b149ad5d6959438c6f291e2426c86df3b874c525b30faad51b0d96b3.js:25
    promise callback*registerControllerFromPath [REDACTED]/assets/stimulus-loading-3576ce92b149ad5d6959438c6f291e2426c86df3b874c525b30faad51b0d96b3.js:25
    eagerLoadControllersFrom [REDACTED]/assets/stimulus-loading-3576ce92b149ad5d6959438c6f291e2426c86df3b874c525b30faad51b0d96b3.js:9
    eagerLoadControllersFrom [REDACTED]/assets/stimulus-loading-3576ce92b149ad5d6959438c6f291e2426c86df3b874c525b30faad51b0d96b3.js:9
    <anonymous> [REDACTED]/assets/controllers/index-281c86b7ad1612bd967760cbd501c66fe8bda0dff0c11ef4b93cd940f3c1956b.js:5
```

If I manually go to the `/api/v1/points/tracked_months` endpoint I get a response similar to this (but with more years in the list):

```
[2024,2023,2022]
```

**Comment by tomudding** [comment]
I assume very much related, trying to manually start the stats calculation job (from the stats menu) throws a similar error on the back-end side of things:

![image](https://github.com/user-attachments/assets/94886c8d-e17a-44f2-a9d8-b748c8f92321)

**Comment by tomudding** [comment]
The difference in the output format is a change in `0.20.0`, so in theory, it should just work:

https://github.com/Freika/dawarich/compare/0.19.7...0.20.0#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29b

But it keeps returning the data in the old format. I checked in the container, but everything is fully up-to-date with the code from `0.20.0`/`0.20.1` (i.e. the new format).

**Comment by tomudding** [comment]
> @tomudding try this:
> 
>     1. Go to the console: https://dawarich.app/docs/FAQ#how-to-enter-dawarich-console
>     2. Find your user id: `id = User.find_by(email: 'YOUR@EMAIL.TLD')`
>     3. Clear cache for the endpoint: `Rails.cache.delete("dawarich/user_#{id}_years_tracked")
> 
> 
> Then try again and check if your problem is still there

That worked! Thank you very much :)

It is interesting that the faulty information ended up in the Redis cache, as I started with a new installation (on a different server) and https://dawarich.app/docs/tutorials/backup-and-restore#restore but I do not think we will ever be able to determine how that happened.
