### ISSUE TITLE
[bug][firefox] 'Error loading year'

### ISSUE THREAD

**Issue by shaman007** [Freika/dawarich#562]
**Describe the bug**
'Error loading year'

**Version**
0.20.1, Firefox 133.0.3 

**To Reproduce**
![image](https://github.com/user-attachments/assets/9ed1fd41-916b-4bd0-9a9d-63abfc02a8df)

**Comment by Freika** [comment]
Try this: https://github.com/Freika/dawarich/issues/558#issuecomment-2548415601

**Comment by Beer17HWAM** [comment]
Same here, fixed it with https://github.com/Freika/dawarich/issues/558#issuecomment-2548415601.
Why did you change the layout? Now the links on the cities are not available anymore. I prefered the old layout.

**Comment by Freika** [comment]
@Beer17HWAM not sure what are you referring to, cities in the sidebar had no links. The layout c change was made to make more space for the map itself and to make navigation collapsible.

I'm closing this issue for now, it should not be a problem any more
