### ISSUE TITLE
The new (since 0.20.0) calendar map popup is showing "Error loading years"

### ISSUE THREAD

**Issue by TheCommishDeuce** [Freika/dawarich#572]
**Describe the bug**
The bug concerns lack of year_month choice in the new calendar view on the map tab.

**Version**
0.21.0

**To Reproduce**
Update from a pre-0.20.0 to the latest version

**Expected behavior**
to have a month matrix with a years dropdown menu

**Screenshots**
<img width="517" alt="image" src="https://github.com/user-attachments/assets/711bebb4-a4a5-43b5-b92d-7445cfdd425c" />

**Comment by Beer17HWAM** [comment]
See https://github.com/Freika/dawarich/issues/558

**Comment by TheCommishDeuce** [comment]
Thank you, that helped :)
