### ISSUE TITLE
PFSENSE HAProxy issue

### ISSUE THREAD

**Issue by schneemaier** [Freika/dawarich#573]
**Describe the bug**
I am trying to use the service behind a pfsense firewall and haproxy

**Version**
0.21.0

**To Reproduce**
1. Install service with docker on a server
2. Configure HAproxy on Pfsense with shared frontend and url matching
3. Connect to Dawarich server from outside
4. Try to login, but login fails, the login page reloads. 

**Expected behavior**
Login completed

**Screenshots**

**Logs**
Chrome console log sows 422 error:
```
POST https://gps.uxxxxx.xxxu:8000/users/sign_in 422 (Unprocessable Content)
$ @ turbo.es2017-esm.js:766
perform @ turbo.es2017-esm.js:897
await in perform
start @ turbo.es2017-esm.js:1189
submitForm @ turbo.es2017-esm.js:4287
formSubmitted @ turbo.es2017-esm.js:5477
submitBubbled @ turbo.es2017-esm.js:1470Understand this errorAI
Navigated to https://gps.uxxxxx.xxxu:8000/users/sign_in
```
us.schneemaier.h
**Additional context**
Other services like Home Assistant, work behinfd the same HA proxyinstance

**Comment by ajpanton** [comment]
I'm doing the exact same thing, and has always worked flawlessly. Just FYI, that it "should" work, and it can work.

**Comment by schneemaier** [comment]
@ajpanton Can you share the config you are using for HA Procy in PFSENSE? I know it should workm, but currerntly I am clueless why it is not working.

Note that I tried it using stunnel and port wforwardig instead on the router, and have the same result. Maybe something in the in docker-compose.yaml is not correct?

**Comment by ajpanton** [comment]
@schneemaier Here you go, I hope I managed to delete everything sensitive. Also deleted everything about my other ACL's and backends.

I have one front-end that redirects http to https, and then the main one for https.

There are some rules that are auto-generated by HAProxy. They might be specific to the pfSense package, but in any case, you probably have them too (just not visible in the GUI).

<details>
<summary>/var/etc/haproxy/haproxy.cfg</summary>
```
# Automaticaly generated, dont edit manually.
# Generated on: 2024-12-22 06:22
global
        maxconn                 10000
        log                     /var/run/log    local0  debug
        stats socket /tmp/haproxy.socket level admin  expose-fd listeners
        uid                     80
        gid                     80
        nbthread                        4
        hard-stop-after         15m
        chroot                          /tmp/haproxy_chroot
        daemon
        tune.ssl.default-dh-param       2048
        server-state-file /tmp/haproxy_server_state

listen HAProxyLocalStats
        bind 127.0.0.1:2200 name localstats
        mode http
        stats enable
        stats admin if TRUE
        stats show-legends
        stats uri /haproxy/haproxy_stats.php?haproxystats=1
        timeout client 5000
        timeout connect 5000
        timeout server 5000

frontend http-to-https
        bind                    [IP]:80 name [IP]:80
        mode                    http
        log                     global
        option                  http-keep-alive
        timeout client          30000
        http-request set-var(txn.txnpath) path
        http-request set-var(txn.txnhost) hdr(host)

frontend https-frontend
        bind                    [IP]:443 name [IP]:443   ssl crt-list /var/etc/haproxy/https-frontend.crt_list
        mode                    http
        log                     global
        option                  httplog
        option                  http-keep-alive
        option                  forwardfor
        acl https ssl_fc
        http-request set-header         X-Forwarded-Proto http if !https
        http-request set-header         X-Forwarded-Proto https if https
        timeout client          30000

        acl                     dawarich        var(txn.txnhost) -m beg -i [dawarich.example.com]
        acl                     aclcrt_https-frontend   var(txn.txnhost) -m reg -i ^([^\.]*)\.[example]\.[com](:([0-9]){1,5})?$
        acl                     aclcrt_https-frontend   var(txn.txnhost) -m reg -i ^[example]\.[com](:([0-9]){1,5})?$
        http-request set-var(txn.txnpath) path
        http-request set-var(txn.txnhost) hdr(host)

        use_backend Dawarich_ipvANY  if  dawarich aclcrt_https-frontend

backend Dawarich_ipvANY
        mode                    http
        id                      120
        log                     global
        timeout connect         5000
        timeout server          30000
        retries                 2
        load-server-state-from-file     global
        server                  dawarich [local IP]:3000 id 116 check inter 5000
```
</details>

**Comment by schneemaier** [comment]
@ajpanton Thank you! I found out that my frontend setting was missing one option.
```
	option			forwardfor
	acl https ssl_fc
```

Added this one setting via the UI and dawarich started to work :)

**Comment by alternativesurfer** [comment]
> @ajpanton Thank you! I found out that my frontend setting was missing one option.
> 
> ```
> 	option			forwardfor
> 	acl https ssl_fc
> ```
> 
> Added this one setting via the UI and dawarich started to work :)

@schneemaier what was the actual setting/where is in within the frontend settings in the GUI? I feel like I am blind and this exact thing is happening to me.

**Comment by schneemaier** [comment]
@alternativesurfer the forward for option is called `Use "forwardfor" option` on the GUI. I have enabled this for hte shared frontend

![image](https://github.com/user-attachments/assets/62e35ca5-4bab-4fc1-984c-13764f250991)

**Comment by alternativesurfer** [comment]
Lifesaver, that did it!

Thank you so much, @schneemaier !!!


And for anyone on OPNSense, they've moved it to the backend entries:
backendX > HTTP SETTINGS > (check) Forwarded Header & X-Forwarded-For Header
