### ISSUE TITLE
Import not complete

### ISSUE THREAD

**Issue by Tazmanian79** [Freika/dawarich#63]
I have downloaded my Google Time line history via Google Take Out.   And I have uploaded all Google_semantic_history to Dawarich.
All files are completed.  But not all history seems to show up in Dawarich.  For example 2024 no history for april/may/juin.

I have location history from 2012.  But several months are empty.

Also on the Map page I can only select year 2024 and 2023, all years before are not showing up.

![Schermafbeelding 2024-06-14 083159](https://github.com/Freika/dawarich/assets/2421824/fbcc6be2-633c-4687-9671-f38ceb47f31e)
![Schermafbeelding 2024-06-14 083237](https://github.com/Freika/dawarich/assets/2421824/613f1249-b145-4f4a-94d2-3847c2640ae7)
![history](https://github.com/Freika/dawarich/assets/2421824/f463bd43-d752-4e65-8013-b250682dd603)

**Comment by Freika** [comment]
Hi @Tazmanian79! Please try uploading problematic files again and provide logs from `dawarich_app` and `dawarich_sidekiq` containers around the time of importing attempt

**Comment by Freika** [comment]
@Tazmanian79 did it eventually work for you?

**Comment by Tazmanian79** [comment]
@Freika sorry I did a reinstall and now I'm importing the Records.json from my timeline.  But will take several days before it's completed.  History since 2011 and now more than 24h later i'm at 11/2013 ... so 11 more years to go.  Think import will take 2 weeks.

At this moment: 502,770  Geopoints tracked

**Comment by Freika** [comment]
Got it, let me know once the import is finished :) You can increase number of concurrent jobs by changing `BACKGROUND_PROCESSING_CONCURRENCY` env var, upto 100 should work good.

**Comment by Tazmanian79** [comment]
Yeah probably should have changed that.  But of i do now i Will need to rebuild thé container and Will have to restart thé whole process?

**Comment by Freika** [comment]
If command you had to run to import Records.json succesfully completed, you're good to restart the app completely: background jobs data is being stored in Redis which is being run as part of your docker-compose.yml stack. You can stop your `dawarich_sidekiq` container, update `BACKGROUND_PROCESSING_CONCURRENCY` value and start it again, process will continue.

**Comment by Tazmanian79** [comment]
Ok Will try it tomorrow.  The import was completed yes, so it should work.  Keep you posted.

**Comment by Tazmanian79** [comment]
Changed the value , restarted and it's processing again.
Hope it goes faster now.  Will let you know when the import is finished.

The Google_semantic_history is also neccassary to have same as in Google Timeline oris Records.json enough?

**Comment by Freika** [comment]
> The Google_semantic_history is also neccassary to have same as in Google Timeline oris Records.json enough?

Google Semantic History might have a number of points that are not recorded in Records.json, so it's better to at least try to import them

**Comment by Tazmanian79** [comment]
All is imported now on 2 accounts.  Records.json and Google Semantic
