### ISSUE TITLE
CookieOverflow when import owntracks rec file

### ISSUE THREAD

**Issue by norangebit** [Freika/dawarich#73]
**Describe the bug**
When i try to import a `.rec` file a get a CookieOverflow error.

```
       def check_for_overflow!(name, options)
          if options[:value].bytesize > MAX_COOKIE_SIZE
            raise CookieOverflow, "#{name} cookie overflowed with size #{options[:value].bytesize} bytes"
          end
        end
    end
```

**Version**
0.7.1

**To Reproduce**
1. Import a `.rec` file

**Expected behavior**
The file is correctly imported

**Comment by flesser** [comment]
Same here trying to import a 8.4 MB *.gpx file

**Comment by Freika** [comment]
@norangebit there is no support for `.rec` files at the moment. To be honest, I expected OwnTracks users to do a bit different export: in OwnTracks web interface, in the top right corner there is a "download" button which allows you to download your data in JSON format. This JSON file should be correctly imported to Dawarich. Can you try doing it this way? Thanks!

<img width="134" alt="изображение" src="https://github.com/Freika/dawarich/assets/3738638/076c43bb-d76e-45ea-84f9-1c5764a6896f">

**Comment by Freika** [comment]
@flesser can you please show logs of `dawarich_sidekiq` and `dawarich_app` around time of the importing attempt?

**Comment by norangebit** [comment]
@Freika it works using the json. Thanks

**Comment by Freika** [comment]
@norangebit I'll consider adding support for .rec files and will update instructions for importing OwnTracks files :)
