### ISSUE TITLE
Can't push data from Overland (api_key)

### ISSUE THREAD

**Issue by a-camacho** [Freika/dawarich#78]
**Describe the bug**
Data pushed from Overland app does not work.
App does not give error, but Dawarich logs show that api_key parameter was not expected.

**Version**
0.7.1

**Expected behavior**
Data to be saved on Dawarich

**Logs**

```
10:28:11 web.1  | Unpermitted parameter: :api_key. Context: { controller: Api::V1::Overland::BatchesController, action: create, request: #<ActionDispatch::Request:0x00007f58c9c25b40>, params: {"locations"=>[{"type"=>"Feature", "geometry"=>{"type"=>"Point", "coordinates"=>[6.1356262, 46.2038273]}, "properties"=>{"speed"=>-1, "battery_state"=>"unplugged", "motion"=>[], "timestamp"=>"2024-06-22T15:57:35Z", "horizontal_accuracy"=>35, "speed_accuracy"=>-1, "vertical_accuracy"=>21, "battery_level"=>0.15, "wifi"=>"", "course"=>-1, "device_id"=>"xxxx-iphone", "altitude"=>375, "course_accuracy"=>-1}}, .............. }
```

**Comment by Freika** [comment]
It turned out there was no problem and points were being sent and accepted correctly. `Unpermitted parameter: :api_key` message in logs does not indicate a problem of any kind and is expected behavior.
