### ISSUE TITLE
Blocked host after setting up public domain

### ISSUE THREAD

**Issue by janaxhell** [Freika/dawarich#79]
**Describe the bug**
If I try to access darawich through my cloudflare domain, I get this error

```
Blocked hosts: XXX.XXX.XXX
To allow requests to these hosts, make sure they are valid hostnames (containing only numbers, letters, dashes and dots), then add the following to your environment configuration:
    config.hosts << "XXX.XXX.XXX"
```
I have added that line at the end of 
`/config/environments/development.rb`
but it doesn't work.

**Version**
0.7.1

**To Reproduce**
1. Open Darawich via domain

**Expected behavior**
To work with no error

**Screenshots**
![image](https://github.com/Freika/dawarich/assets/55061479/757a2a06-6e30-4b1f-83ac-de484f77e98b)

**Logs**
11:35:48 web.1  | [ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked hosts: XXX.XXX.XXX

**Comment by b-A-shi** [comment]
Had the same problem, the solution was kinda easy. 

Within docker compose - change the APPLICATION_HOST: Env to your domain.

**Comment by janaxhell** [comment]
Ouch, silly me. Works fine, thank you!

**Comment by zerojay** [comment]
For anyone coming here afterwards, when setting up APPLICATION_HOST for your domain, make sure it is just the subdomain.domain.tld, do not include the https:// or http:// as part of it or it will fail the same way.

**Comment by MrColumbo** [comment]
i got the same issue but i wanted to mention that the documentation mentions APPLICATION_HOSTS (plural) and i first added all the host (kept the local host and added mine (comma separated) ....than I thought i accidentally deleted the s from HOSTS and changed the var in the wrong way.

Long story short - it works now for me but i guess the reverse proxy documentation is a bit outdated

**Comment by kannszzz** [comment]
I am facing same issue and i have updated as per the documents in application_host and application_hosts and still facing issue. Whats the difference between the two variable? 

Application_Host: "tld.domain.com"
Application_Hosts: "tld.domain.com,domain.com,127.0.0.1" 

Any idea what might be the issue. I have set it on local proxy using nginxpm

**Comment by Freika** [comment]
> I am facing same issue and i have updated as per the documents in application_host and application_hosts and still facing issue. Whats the difference between the two variable?
> 
> Application_Host: "tld.domain.com" Application_Hosts: "tld.domain.com,domain.com,127.0.0.1"
> 
> Any idea what might be the issue. I have set it on local proxy using nginxpm

It may be called legacy, they will be unified in one. Are they both in upper case in your compose file?

**Comment by kannszzz** [comment]
Yeah, I got the compose file from git. Is there another location to get the latest compose?
Original code
```
APPLICATION_HOST: localhost
APPLICATION_HOSTS: localhost
```

**Comment by Tarydium** [comment]
It worked on my last iteration. Just updated to the last release and now i get the blocked host error accessing using my domain.
      APPLICATION_HOST: maps.domain.org
      APPLICATION_HOSTS: localhost, dawarich.domain.lan, maps.domain.org

domain = mydomain

**Comment by kokesh** [comment]
I'm trying to run Dawarich with my_domain.com:6001, but still getting blocked host error

![Image](https://github.com/user-attachments/assets/adbb6b92-a143-4005-a20d-5f1ddef14453)

**Comment by Freika** [comment]
@kokesh you probably need to add your domain with port since you're using it to access the app

**Comment by kokesh** [comment]
@Freika I've tried, but it doesn't change anything

**Comment by kymograph** [comment]
It is important to list the domains without spaces after the comma. This was not obvious and caused me some headache.
