### ISSUE TITLE
Still issue with Distance Calculation from Google Imports 

### ISSUE THREAD

**Issue by jay-oswald** [Freika/dawarich#83]
**Describe the bug**
Same as #53 but I just installed and imported a few days ago.

In 2019 I did go overseas for the first time in many years, so expected the travel to be higher. The distribution is also all wrong, went overseas sep/oct, from Australia to UK. My best guess on whats happening is the dates were parsed wrong (or stored wrong from google?) and it thinks I've gone back and fourth from Aus to UK over and over causing the very high km's

**Version**
Include version of Dawarich you're experiencing problem on.

**To Reproduce**
1. Fresh Dawarich Install
2. Import a google file
4. See error (hopefully? Probably a bad/weird file)

**Expected behavior**
Distribution should be fairly even, with spike in september/october.

**Screenshots**
![image](https://github.com/Freika/dawarich/assets/16188552/7dc4015a-120e-4867-9e51-9771aa29d30b)

**Comment by Freika** [comment]
Can you show me the result of the following?

1. On your server, run `docker exec -it CONTAINER_ID /bin/sh` to enter dawarich app container sh
2. Run `bin/rails console` to enter Rails console
3. `points = Point.where('longitude = 0.0 OR latitude = 0.0')`

This should return an array of points with lon or lat being 0. I'm interesting in `raw_data` column, so if you could send here result of `points.map(&:raw_data)`, it would make it easier for me to debug the problem.

Thanks!

**Comment by jay-oswald** [comment]
There was only 2 points returned from that, both had lat and lng as `0.0`. Both were also from 2023. It also returned a whole object for each of them, here is 1 of them if it helps at all

```
[#<Point:0x000014e9aeaca920
  id: 2791436,
  battery_status: nil,
  ping: nil,
  battery: nil,
  tracker_id: "google-maps-timeline-export",
  topic: "Google Maps Timeline Export",
  altitude: nil,
  longitude: 0.0,
  velocity: nil,
  trigger: nil,
  bssid: nil,
  ssid: nil,
  connection: nil,
  vertical_accuracy: nil,
  accuracy: nil,
  timestamp: 1703283482,
  latitude: 0.0,
  mode: nil,
  inrids: [],
  in_regions: [],
  raw_data:
   {"osLevel"=>34,
    "activity"=>
     [{"activity"=>
        [{"type"=>"UNKNOWN", "confidence"=>41},
         {"type"=>"IN_VEHICLE", "confidence"=>10},
         {"type"=>"ON_BICYCLE", "confidence"=>10},
         {"type"=>"ON_FOOT", "confidence"=>10},
         {"type"=>"STILL", "confidence"=>10},
         {"type"=>"WALKING", "confidence"=>10},
         {"type"=>"RUNNING", "confidence"=>10},
         {"type"=>"IN_ROAD_VEHICLE", "confidence"=>10},
         {"type"=>"IN_RAIL_VEHICLE", "confidence"=>10}],
       "timestamp"=>"2023-12-22T22:17:00.567Z"},
      {"activity"=>
        [{"type"=>"ON_FOOT", "confidence"=>92},
         {"type"=>"WALKING", "confidence"=>92},
         {"type"=>"RUNNING", "confidence"=>3},
         {"type"=>"IN_VEHICLE", "confidence"=>2},
         {"type"=>"IN_RAIL_VEHICLE", "confidence"=>2},
         {"type"=>"ON_BICYCLE", "confidence"=>1},
         {"type"=>"UNKNOWN", "confidence"=>0},
         {"type"=>"IN_ROAD_VEHICLE", "confidence"=>0}],
       "timestamp"=>"2023-12-22T22:17:51.169Z"}],
    "deviceTag"=>1514923761,
    "timestamp"=>"2023-12-22T22:18:02.540Z",
    "formFactor"=>"PHONE",
```

**Comment by Freika** [comment]
@jay-oswald the `raw_data` seems to be incomplete, but does it have anything similar to `latitude` and `longitude`, might be spelled as `lat`/`lon` or `latitudeE7`/`longitudeE7`?

**Comment by jay-oswald** [comment]
@Freika yeah the raw data seamed to get cut off by the rails function to search for it, though in the section that made it to my console there was both `latitude` and `longitude` in there both set to `0.0`. So obvisually bad points, but also just 2 of them, so 2 bad points shouldn't stuff up the whole year of data? Must be something else?

**Comment by Freika** [comment]
@jay-oswald there is a chance it might be related to https://github.com/Freika/dawarich/issues/60. It would be great if you could find points that are close to each other in time but far away distance-wise, that would confirm this theory. You can try to narrow it down by visiting yeat's stat (i.e. http://localhost:3000/stats/2024) and find days with the biggest traveling distances, and then try to find these points on your Points page (i.e. http://localhost:3000/points)

**Comment by jay-oswald** [comment]
![image](https://github.com/Freika/dawarich/assets/16188552/b7344fea-bf5a-4810-a1c1-5bd48e00e34d)
@Freika side note, but adding commas for number formating would make these things way easier to read in general, but especally when looking at this issue because the numbers are so big

Looking at the month by month data, it looks like most of the data is good, just a few months where I'm assuming there must have been lots of back and fourth. Like April its flagged it as visiting the middle east (which I didn't), while I was auctally home. So there must just be some bad data. There was a bunch of points where every few seconds it thinks I went between Melbourne and the middle east.

This could just be bad data, but I have tried to find the points in the data, and seams like Google stores them as `latitudeE7` and they are not auctally GPS coords? Since the coords in in Dawarich are not found in the google data. However the google data does have Melbourne and the middle east in the data. So I think this is not an issue with Dawarich, but just my google data is bad.

I'm thinking to fix the data since I wasn't in the middle east I could write some SQL to just delete bad data points, e.g. I didn't leave Australia in April 2019, so I can delete all data points with a positive lat from April 2019 etc, and I can clean up the data that way, then re-calc stats

**Comment by Freika** [comment]
So it's really the bad coordinate thing. Yeah, it was reported from another user too, seems like Google not always writes them correctly. The simple idea of how to filter out incorrect points is to disregard ones placed too far away from a previous one that are also very close in time to a previous one, but I already feel like it will not be as reliable from the very first version and will require some tweaking

**Comment by Freika** [comment]
Closing this in favour of https://github.com/Freika/dawarich/issues/60
