### ISSUE TITLE
Import GPX, processed 0/0

### ISSUE THREAD

**Issue by andreapx** [Freika/dawarich#90]
**Describe the bug**
I'm trying to import some GPX files (created with GPSLogger (Android app, [this one](https://github.com/mendhak/gpslogger)), but after I select the file and click the import button, in the imports page I see the filename with 0/0 processed.
In the map I see some small tracks but not the full track I've imported.
In the stats I see the total points (should be correct) and the total KM (also should be correct).

**Version**
0.8.0

**To Reproduce**
1. Go to 'Imports'
2. Click on 'New import'
3. Scroll down to 'GPX'
4. Select file
5. click on 'Create import'

**Expected behavior**
In the map I think that there should be the full tracks and in the imports section all the import should have */* instead of 0/0

**Screenshots**
![image](https://github.com/Freika/dawarich/assets/13846728/e4c53cdf-7476-476b-a417-efcb2ab1d173)

**Logs**
I don't know what file you need, let me know

**Additional context**
Is there a way to upload multiple GPX files simultaneously?

**Comment by Freika** [comment]
The numbers on the Imports page are a bit broken at the moment, in the next release it will be fixed.

As for the route not being drawn as expected, here is how it works:

>  In the first versions, Dawarich rendered one single route that connected all the points on the map. It made the map kind of unreadable (see the screenshot). One of my friends suggested splitting routes based on time and distance between consecutive points. The idea looks like this: points are being connected to form a route on the map unless the time between one of the points and the other is more than 1 hour. If that's the case, these points are not being connected, and the route ends. The same goes for distance: if the distance between two consecutive points is more than 500 meters, the route ends. These conditions are working on an "OR" basis, if one of them is true, the route ends. 

You can change settings for route splitting on /settings page of your Dawarich instance

<img width="481" alt="изображение" src="https://github.com/Freika/dawarich/assets/3738638/7e721a36-e8c9-4021-86c9-1ae9fce71526">

>  Is there a way to upload multiple GPX files simultaneously?

You can just select multiple files at step 4 of your "How to reproduce" section :)

**Comment by Freika** [comment]
Imports page have been fixed in https://github.com/Freika/dawarich/releases/tag/0.8.1

**Comment by andreapx** [comment]
>Imports page have been fixed in https://github.com/Freika/dawarich/releases/tag/0.8.1
>

Wow, cool!!!
 
> As for the route not being drawn as expected, here is how it works:
> 
> > In the first versions, Dawarich rendered one single route that connected all the points on the map. It made the map kind of unreadable (see the screenshot). One of my friends suggested splitting routes based on time and distance between consecutive points. The idea looks like this: points are being connected to form a route on the map unless the time between one of the points and the other is more than 1 hour. If that's the case, these points are not being connected, and the route ends. The same goes for distance: if the distance between two consecutive points is more than 500 meters, the route ends. These conditions are working on an "OR" basis, if one of them is true, the route ends.
> 
> You can change settings for route splitting on /settings page of your Dawarich instance

Thanks, that solved my doubt!

 
> > Is there a way to upload multiple GPX files simultaneously?
> 
> You can just select multiple files at step 4 of your "How to reproduce" section :)

Ah, so easy, thanks a lot!!!

When I try to import multiple files sometimes I get the error (when the total file weight is bigger):

```
<html><body>
<!--StartFragment--><header>
  <h1>
    ActionDispatch::Cookies::CookieOverflow
      in ImportsController#create
  </h1>
</header>

<main role="main" id="container">
    <div class="exception-message">
    <div class="message">_dawarich_session cookie overflowed with size 24900 bytes</div>
  </div>

  


  
    <div class="source " id="frame-source-0-0">
      <div class="info">
        Extracted source (around line <strong>#597</strong>):
      </div>
      <div class="data">
        
595 596 597 598 599 600 | def check_for_overflow!(name, options)           if options[:value].bytesize > MAX_COOKIE_SIZE             raise CookieOverflow, "#{name} cookie overflowed with size #{options[:value].bytesize} bytes"           end         end     end
-- | --


</div></div></main><!--EndFragment-->
</body>
</html>
```

**Comment by Freika** [comment]
What kind of files you're trying to import and what sizes they are of?

**Comment by andreapx** [comment]
> What kind of files you're trying to import and what sizes they are of?

The files have been created by GPSLogger and I'm able to import them, only when the total size is under a certain amount (I don't know how much).
The size of the files varies from 1KB to 110KB. When I had the error the total size was 968KB.

**Comment by Freika** [comment]
Okay, `CookieOverflow` is something new to me, so I'll try to find time to investigate it. Feel free to open another issue with your problem description, so it's not lost :)

**Comment by MrColumbo** [comment]
not sure if i have the same issue. I just installed the app  - default docker compose and i tried to import GPX and JSON (google semantic) and it look like that. I see all the files but 0 points.
I noticed that the sidekick container exits sooner or later ( dawarich_sidekiq exited with code 1 ) but from a GUI point of view everything looks fine in general .....but the import does not seem to process the files at all (please let me know if rather should open up a new issue .....not quite sure if mine might be completely different)

**Comment by Freika** [comment]
@MrColumbo you can try to simply restart sidekiq container and see if it works for you, and if it's not, feel free to provide logs with errors 👋

**Comment by MrColumbo** [comment]
It is already working after the upgrade. Thanks for your support:)

Yahoo Mail: Suchen, organisieren, erobern 
 
  Am Di., Juli 9, 2024 at 19:58 schrieb Evgenii ***@***.***>:   


@MrColumbo you can try to simply restart sidekiq container and see if it works for you, and if it's not, feel free to provide logs with errors 👋
