### ISSUE TITLE
Discussion: Home Assistant integration that would write to Dawarich from it's mobile app data

### ISSUE THREAD

**Issue by Schonhoffer** [Freika/dawarich#98]
This isn't a feature request and hopefully wouldn't require any changes in the Dawarich codebase. Just starting a place where maybe someone could point out any potential blockers/gotchas, and maybe help find other people interested in contributing.

Many self-hosters are already running the Home Assistant mobile app which periodically sends location data in both long/lat and geo-coded to the self-hosted home assistant instance. The idea would be to write a dawarich-home-assistant integration (in python, different repository). That integration would run inside the home assistant server process (not the mobile app). It would be configured to forward the geo-data already transmitted by the home assistant app to a Dawarich endpoint. 

The main advantage would just be to not have to configure a separate mobile app. Although Dawarich would also be a good candidate to eventually become a "Home assistant OS Addon" which could auto-install Dawarich on home assistant OS machines.

**Comment by Freika** [comment]
There is a guide from another user on how to setup HA->Dawarich data sending integration, you might be interested: https://github.com/Freika/dawarich/discussions/77#discussioncomment-9904099

**Comment by Schonhoffer** [comment]
Oh wow, easy! Maybe I'll just start with that that rest_command approach and only look into an integration if it needs more complexity,

You're missing out on home-assistant!
