### ISSUE TITLE
failed to import

### ISSUE THREAD

**Issue by brjppru** [Freika/dawarich#99]
dawarich_sidekiq  | 2024-07-04T09:02:46.244Z pid=54 tid=jj2 class=Owntracks::PointCreatingJob jid=562915e75de19d58624207c2 elapsed=0.012 INFO: fail
dawarich_sidekiq  | 2024-07-04T09:02:46.244Z pid=54 tid=jj2 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","wrapped":"Owntracks::PointCreatingJob","args":[{"job_class":"Owntracks::PointCreatingJob","job_id":"02af27e7-c993-4a42-af34-fcc1c00c611a","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_type":"status","iOS":{"deviceSystemName":"iOS","localeUsesMetricSystem":true,"locationManagerAuthorizationStatus":"kCLAuthorizationStatusAuthorizedAlways","version":"17.3.1","altimeterIsRelativeAltitudeAvailable":true,"deviceIdentifierForVendor":"8322C8E2-D1EB-4D5D-9C32-3DFE01F3855C","deviceSystemVersion":"17.5.1","locale":"en_KZ","altimeterAuthorizationStatus":"CMAuthorizationStatusNotDetermined","deviceModel":"iPhone","deviceUserInterfaceIdiom":"UIUserInterfaceIdiomPhone","backgroundRefreshStatus":"UIBackgroundRefreshStatusAvailable","_aj_hash_with_indifferent_access":true},"topic":"owntracks/user/8322C8E2-D1EB-4D5D-9C32-3DFE01F3855C/status","api_key":"d23e483fb1ec0d0fd31033d72d9ba525","controller":"api/v1/owntracks/points","action":"create","point":{"topic":"owntracks/user/8322C8E2-D1EB-4D5D-9C32-3DFE01F3855C/status","_aj_hash_with_indifferent_access":true},"_aj_hash_with_indifferent_access":true},2],"executions":0,"exception_executions":{},"locale":"en","timezone":"Asia/Almaty","enqueued_at":"2024-07-04T08:58:57.774551964Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"562915e75de19d58624207c2","created_at":1720083537.7746055,"enqueued_at":1720083766.231706,"error_message":"Validation failed: Latitude can't be blank, Longitude can't be blank","error_class":"ActiveRecord::RecordInvalid","failed_at":1720083537.7866502,"retry_count":3,"retried_at":1720083636.4999638}}

what i should fix in owntracker ?

**Comment by chrisl8** [comment]
I have the same problem. I ended up using the Overland GPS Tracker instead. It works for me and seems better suited to my goals and to use with this service anyway.

**Comment by brjppru** [comment]
change from GET, to POST metod.

i solve for me this bug

**Comment by chrisl8** [comment]
@brjppru Can you explain how you set Owntracks to POST instead of GET? I don't see any configuration option for doing that in the Owntracks app, and the documentation seems to indicate that it is always a POST, not a GET.

It doesn't even make sense that Owntracks would be trying to send JSON via GET request to begin with.

I still get this problem with Owntracks, so it isn't solved for me, but I can open another issue if we like.

**Comment by Freika** [comment]
@chrisl8 can you share your logs?

**Comment by chrisl8** [comment]
Thanks for responding, I got busy. I think I will just stick with Overland for now. It is cumbersome for me to test two apps at once.

If nobody else is having this problem, I'll assume it is some quirk of my setup.

Someone can tag me again if they are having the same problem and I'll dig into it, but for my part I'm going to stick with Overland.

**Comment by Freika** [comment]
> 2024-10-02T21:35:15.897Z pid=81 tid=hjp WARN: ActiveRecord::RecordInvalid: Validation failed: Latitude can't be blank, Longitude can't be blank

This indicates a point (or points) without lat/lon attributes.

@rhyst is it a .json file or a .bin file you're trying to import?

**Comment by rhyst** [comment]
This is an error I get when trying to use Owntracks to push my current location.

**Comment by Freika** [comment]
Right, I didn't notice that.

```
I, [2024-10-02T21:35:15.881691 #81]  INFO -- : Performing Owntracks::PointCreatingJob (Job ID: 56c36708-f5ad-449f-98af-a69fcc386eb6) from Sidekiq(default) enqueued at 2024-10-02T21:26:36.511089682Z with arguments: {"_type"=>"status", "_id"=>"eaf2c30f", "android"=>{"hib"=>0, "bo"=>0, "loc"=>0, "ps"=>0, "wifi"=>1}, "topic"=>"owntracks/me/phone/status", "api_key"=>"apikey", "controller"=>"api/v1/owntracks/points", "action"=>"create", "point"=>{"topic"=>"owntracks/me/phone/status"}}, 1
```

Your owntracks client did not send any coordinates, so nothing to be created in Dawarich 🤷

**Comment by rhyst** [comment]
Ah there are a couple of recent issues on the owntracks github for missing locations etc. related to a recent android update. Possibly the cause, but probably not Dawarich 😬

**Comment by Freika** [comment]
@rhyst please let me know if they fix this
